New tests for controllers uncovered methods
ita-social-projects/EPlast pull request #1049
Opened 2021-03-12 19:32 UTC by Oleh-Bodnar

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-03-13 06:52 UTC, OlehHatsko approved these changes

2021-03-13 07:14 UTC, sooooolo commented on EPlast/EPlast.Tests/Controllers/EducatorsStaffControllerTests.cs
> +                ID = 1
magic number

2021-03-13 07:14 UTC, sooooolo commented on EPlast/EPlast.Tests/Controllers/DistinctionControllerTests.cs
>  }
All files should end with an empty row

2021-03-13 07:26 UTC, sooooolo requested changes

2021-03-13 07:26 UTC, sooooolo commented on EPlast/EPlast.Tests/Controllers/EventsUsersControllerTests.cs
> +            var expectedId = 1;
magic number

2021-03-13 07:26 UTC, sooooolo commented on EPlast/EPlast.Tests/Controllers/EducatorsStaffControllerTests.cs
> +                ID = 1
magic number

2021-03-13 07:26 UTC, sooooolo commented on EPlast/EPlast.Tests/Controllers/PrecautionControllerTests.cs
>  }
add empty row

2021-03-13 07:26 UTC, sooooolo commented on EPlast/EPlast.Tests/Controllers/EventsUsersControllerTests.cs
> +
add an empty row at the end of the file, use Codemaid, it can do that automatically for you

2021-03-13 12:10 UTC, sooooolo requested changes
Change names by adding Test ending

2021-03-13 15:47 UTC, sooooolo approved these changes

2021-03-13 15:52 UTC, sooooolo requested changes

2021-03-13 15:52 UTC, sooooolo commented on EPlast/EPlast.Tests/Controllers/EducatorsStaffControllerTests.cs
> +                ID = 1
magic number

2021-03-13 17:54 UTC, sooooolo approved these changes

2021-03-14 15:40 UTC, MahotskyiO approved these changes

2021-03-14 15:41 UTC, merged