Users table filter procedure
ita-social-projects/EPlast pull request #1073
Opened 2021-03-29 16:39 UTC by sooooolo

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-03-29 18:29 UTC, vovikboyko approved these changes

2021-03-29 18:38 UTC, randomVovaKuhot approved these changes

2021-03-29 18:42 UTC, Lunaflumen approved these changes

2021-03-29 19:14 UTC, LanchevychMaxym requested changes

2021-03-29 19:14 UTC, LanchevychMaxym commented on EPlast/EPlast.DataAccess/Entities/UserEntities/UserTableObject.cs
> +        public int cnt { get; set; }
??

2021-03-29 19:14 UTC, LanchevychMaxym commented on EPlast/EPlast.DataAccess/Repositories/Realizations/Admin/AdminTypeRepository.cs
> +            int count = num[0];
Неймінги

2021-03-29 19:14 UTC, LanchevychMaxym commented on EPlast/EPlast.DataAccess/Repositories/Realizations/User/UserRepository.cs
> +        }
це ж вроді написано було в АдмінРепозиторії, воно точно тут має бути?

2021-03-29 19:14 UTC, LanchevychMaxym commented on EPlast/EPlast.WebApi/Controllers/AdminController.cs
> +        public async Task<IActionResult> UsersTable([FromQuery] TableFilterParameters tableFilterParameters)
Назва методу неправильна, краще GetUsersTableAsync

2021-03-29 19:14 UTC, LanchevychMaxym commented on EPlast/EPlast.BLL/DTO/Admin/ParametersFilter.cs
> +}
ctrl-f каже шо воно тут ніде не юзається

2021-03-29 19:16 UTC, LanchevychMaxym commented
Ще тільки білд пофіксити) А загалом молодець)

2021-04-01 21:39 UTC, LanchevychMaxym requested changes

2021-04-01 21:39 UTC, LanchevychMaxym commented on EPlast/EPlast.BLL/Services/Precautions/UserPrecautionService.cs
> -        private DateTime getPrecautionEndDate(int precautionId, DateTime startDate) {
Назви методів пишуться паскаль кейсом, тобто краще GetPre...

2021-04-01 21:39 UTC, LanchevychMaxym commented on EPlast/EPlast.DataAccess/Entities/UserEntities/UserTableObject.cs
> +        public int cnt { get; set; }
cnt??

2021-04-02 06:08 UTC, LanchevychMaxym approved these changes

2021-04-02 06:34 UTC, merged