Access levels to const roles & registeredUser role not removing bug fix
ita-social-projects/EPlast pull request #1079
Opened 2021-03-30 17:04 UTC by Oleh-Bodnar

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-03-30 21:09 UTC, OlehHatsko requested changes

2021-03-30 21:09 UTC, OlehHatsko commented on EPlast/EPlast.Tests/Services/Admin/AdminServiceTests.cs
> +            await service.ChangeCurrentRoleAsync("id", interested);
magic string

2021-04-01 15:23 UTC, tanyabiryuk approved these changes

2021-04-02 10:15 UTC, danylo-melnychuk approved these changes

2021-04-02 11:27 UTC, sooooolo approved these changes

2021-04-02 16:24 UTC, OlehHatsko approved these changes

2021-04-02 16:34 UTC, merged