View basic info and Secrity Model
ita-social-projects/EPlast pull request #1084
Opened 2021-03-31 18:08 UTC by OlehHatsko

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-03-31 20:09 UTC, voroniak requested changes

2021-03-31 20:09 UTC, voroniak commented on EPlast/EPlast.BLL/DTO/GoverningBody/GoverningBodyProfileDTO.cs
> +        public List<GoverningBodyDocumentsDTO> Documents { get; set; }
It's better to use ienumerable

2021-03-31 20:09 UTC, voroniak commented on EPlast/EPlast.BLL/Interfaces/GoverningBodies/IGoverningBodiesService.cs
> +        Task<Dictionary<string, bool>> GetUserAccess(string userId);
Async

2021-03-31 20:09 UTC, voroniak commented on EPlast/EPlast.BLL/Interfaces/SecurityModel/ISecurityModel.cs
> +        Task<Dictionary<string, bool>> GetUserAccess(string userId, IEnumerable<string> userRoles= null);
Async

2021-03-31 20:09 UTC, voroniak commented on EPlast/EPlast.BLL/Services/GoverningBodies/GoverningBodiesService.cs
> +        public async Task<GoverningBodyProfileDTO> GetProfileById(int id, User user)
Async

2021-03-31 20:09 UTC, voroniak commented on EPlast/EPlast.BLL/Services/GoverningBodies/GoverningBodiesService.cs
> +        public async Task<GoverningBodyDTO> GetProfileById(int id)
Async

2021-03-31 20:09 UTC, voroniak commented on EPlast/EPlast.BLL/Services/RegionBoard/RegionsBoardService.cs
> +        private const string SecuritySettingsFile = "RegionsBoardAccessSettings.json";
Is it correct naming?

2021-03-31 20:09 UTC, voroniak commented on EPlast/EPlast.WebApi/Controllers/GoverningBodiesController.cs
> +            return Ok();
Why did you return empty ok result?

2021-03-31 20:09 UTC, voroniak commented on EPlast/EPlast.WebApi/Controllers/GoverningBodiesController.cs
> +            return Ok();
I'm not sure is it ok to return 200 for delete

2021-03-31 20:09 UTC, voroniak commented on EPlast/EPlast.WebApi/Controllers/RegionsBoardController.cs
> +            return Ok(accesses);
You may write it as 1 line

2021-03-31 21:31 UTC, OlehHatsko commented on EPlast/EPlast.BLL/Interfaces/GoverningBodies/IGoverningBodiesService.cs
> +        Task<Dictionary<string, bool>> GetUserAccess(string userId);
Do you mean to add the `async` keyword to the method declaration? if the answer is yes, then the async keyword can only be used in methods that  have a body

2021-03-31 21:39 UTC, OlehHatsko commented on EPlast/EPlast.BLL/Services/RegionBoard/RegionsBoardService.cs
> +        private const string SecuritySettingsFile = "RegionsBoardAccessSettings.json";
It`s constant, so I used PascalCase. Or did you mean anything else?

2021-03-31 21:43 UTC, OlehHatsko commented on EPlast/EPlast.WebApi/Controllers/GoverningBodiesController.cs
> +            return Ok();
I want to inform the client that it was deleted successfully. Is it better to return nothing?

2021-03-31 21:52 UTC, OlehHatsko commented on EPlast/EPlast.WebApi/Controllers/GoverningBodiesController.cs
> +            return Ok();
200 means that the action was performed successfully. So, I think it`s ok. I haven`t found better solution

2021-04-01 11:56 UTC, atarason requested changes

2021-04-01 11:56 UTC, atarason commented on EPlast/EPlast.BLL/DTO/GoverningBody/GoverningBodyDocumentTypeDTO.cs
> +        public int ID { get; set; }
Could you use Camelcase for naming? should be 'Id' not 'ID'

2021-04-01 11:56 UTC, atarason commented on EPlast/EPlast.BLL/Services/GoverningBodies/GoverningBodiesService.cs
> +            var userAcesses = await _securityModel.GetUserAccessAsync(userId);
Could you combine that two lines into one line?

2021-04-01 11:56 UTC, atarason commented on EPlast/EPlast.BLL/Services/RegionBoard/RegionsBoardService.cs
> +            var userAcesses = await _securityModel.GetUserAccessAsync(userId);
please, combine two lines into one line

2021-04-01 11:56 UTC, atarason commented on EPlast/EPlast.DataAccess/Repositories/Interfaces/GoverningBody/IGoverningBodyAdministrationRepository.cs
> +﻿using System;
please, sort and remove usings

2021-04-01 11:56 UTC, atarason commented on EPlast/EPlast.DataAccess/Repositories/Realizations/Base/RepositoryWrapper.cs
>  using System.Threading.Tasks;
sort usings

2021-04-01 11:56 UTC, atarason commented on EPlast/EPlast.Tests/Controllers/GoverningBodiesControllerTests.cs
>  using System.Security.Principal;
sort usings

2021-04-01 11:56 UTC, atarason commented on EPlast/EPlast.Tests/Controllers/RegionsBoardControllerTests.cs
> +using EPlast.BLL.Interfaces.RegionBoard;
sort usings

2021-04-01 11:56 UTC, atarason commented on EPlast/EPlast.WebApi/Controllers/GoverningBodiesController.cs
> +            return Ok();
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

2021-04-01 11:56 UTC, atarason commented on EPlast/EPlast.WebApi/Controllers/GoverningBodiesController.cs
> +            if (logoName == null)
Can we avoid using if else? I think we can have only if condition

2021-04-08 12:37 UTC, Oleh-Bodnar approved these changes

2021-04-08 12:38 UTC, veronika-kolosova approved these changes

2021-04-09 11:27 UTC, voroniak approved these changes

2021-04-09 12:58 UTC, atarason approved these changes

2021-04-09 12:59 UTC, merged