Added Tests for UserManagerService
ita-social-projects/EPlast pull request #1152
Opened 2021-04-22 17:48 UTC by Vinnytile

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-04-23 08:52 UTC, danylo-melnychuk approved these changes
Welldone

2021-04-24 14:37 UTC, voroniak requested changes

2021-04-24 14:37 UTC, voroniak commented on EPlast/EPlast.Tests/Services/UserManager/UserManagerServiceTests.cs
> +        }
can you move this section to the beginning?

2021-04-24 14:37 UTC, voroniak commented on EPlast/EPlast.Tests/Services/UserManager/UserManagerServiceTests.cs
> +        private readonly UserDTO _userDTO = new UserDTO();
Why don't you use SetUp for this?

2021-04-24 14:37 UTC, voroniak commented on EPlast/EPlast.Tests/Services/UserManager/UserManagerServiceTests.cs
> +    class UserManagerServiceTests
```suggestion
    [TestFixture]
    public class UserManagerServiceTests
```

2021-04-24 14:37 UTC, voroniak commented on EPlast/EPlast.Tests/Services/UserManager/UserManagerServiceTests.cs
> +        [Test]
add space

2021-04-24 14:37 UTC, voroniak commented on EPlast/EPlast.Tests/Services/UserManager/UserManagerServiceTests.cs
> +
?

2021-04-24 15:11 UTC, Vinnytile commented on EPlast/EPlast.Tests/Services/UserManager/UserManagerServiceTests.cs
> +
What's wrong with this part?

2021-04-27 16:33 UTC, tanyabiryuk approved these changes

2021-04-28 17:51 UTC, Oleh-Bodnar approved these changes

2021-04-30 16:51 UTC, voroniak approved these changes

2021-05-04 10:05 UTC, merged