Add DistinctionController tests and PrecautionController tests
ita-social-projects/EPlast pull request #1288
Opened 2021-06-01 16:01 UTC by Tali32

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-06-02 13:31 UTC, tanyabiryuk requested changes

2021-06-02 13:31 UTC, tanyabiryuk commented on EPlast/EPlast.Tests/Controllers/PrecautionControllerTests.cs
> +            var context = new ControllerContext(
It makes sense to create private variable "context" here, as you call constructor for this variable several times.

2021-06-02 14:36 UTC, tanyabiryuk approved these changes

2021-06-03 10:14 UTC, Oleh-Bodnar approved these changes

2021-06-03 11:39 UTC, Vinnytile approved these changes

2021-06-03 11:40 UTC, merged