Cache for cities and clubs
ita-social-projects/EPlast pull request #1365
Opened 2021-06-29 15:23 UTC by veronika-kolosova

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-06-29 15:52 UTC, Oleh-Bodnar approved these changes

2021-06-29 16:17 UTC, christykobyletska approved these changes

2021-06-29 18:03 UTC, sharix4 approved these changes

2021-07-02 13:04 UTC, danylo-melnychuk approved these changes

2021-07-03 11:53 UTC, voroniak requested changes

2021-07-03 11:53 UTC, voroniak commented on EPlast/EPlast.Tests/Controllers/CityCacheControllerTests.cs
> +using EPlast.BLL.DTO.City;
Sort usings

2021-07-03 11:53 UTC, voroniak commented on EPlast/EPlast.Tests/Controllers/ClubCacheControllerTests.cs
> +using EPlast.BLL.Interfaces.Club;
sort usings

2021-07-03 11:53 UTC, voroniak commented on EPlast/EPlast.WebApi/Controllers/ClubCacheController.cs
> +        public ClubCacheController(IClubService clubService,IDistributedCache cache)
format all files. use ctrl + k + d and ctrl + r + g

2021-07-03 11:53 UTC, voroniak commented on EPlast/EPlast.WebApi/Models/City/CitiesViewModel.cs
> +                Cities = from city in cities where city.Name.ToLower().Contains(cityName.ToLower()) select city;
Why don't you use LINQ Extension Methods?

2021-07-03 11:53 UTC, voroniak commented on EPlast/EPlast.WebApi/Models/Club/ClubsViewModel.cs
> +                Clubs = from club in сlubs where club.Name.ToLower().Contains(clubName.ToLower()) select club;
Why don't you use LINQ Extension Methods?

2021-08-10 20:09 UTC, danylo-melnychuk commented
@veronika-kolosova Pls, fix your conflicts and merge this pull request.

2022-01-12 13:00 UTC, closed without merging