Impoved document section
ita-social-projects/EPlast pull request #1366
Opened 2021-06-29 19:00 UTC by christykobyletska

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-06-29 19:46 UTC, sharix4 requested changes
change ip

2021-06-29 19:46 UTC, sharix4 commented on EPlast/EPlast.WebApi/appsettings.json
> +    "Redis": "127.0.0.1:6379"
"Redis": "10.0.95.244:6379" 
must be this IP

2021-06-29 19:54 UTC, sharix4 approved these changes

2021-06-29 20:07 UTC, christykobyletska commented on EPlast/EPlast.WebApi/appsettings.json
> +    "Redis": "127.0.0.1:6379"
done.

2021-06-30 07:39 UTC, Oleh-Bodnar approved these changes

2021-06-30 10:33 UTC, OleksandrBilan approved these changes

2021-06-30 10:55 UTC, merged