About the base
ita-social-projects/EPlast pull request #1421
Opened 2021-07-06 10:32 UTC by veronika-kolosova

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-07-11 12:54 UTC, solomiyon approved these changes

2021-07-11 13:02 UTC, OleksandrBilan approved these changes

2021-07-11 13:11 UTC, andrii52 approved these changes

2021-07-14 14:21 UTC, danylo-melnychuk approved these changes

2021-07-22 09:32 UTC, voroniak requested changes

2021-07-22 09:32 UTC, voroniak commented on EPlast/EPlast.BLL/DTO/AboutBase/SubsectionDTO.cs
> +
delete spaces

2021-07-22 09:32 UTC, voroniak commented on EPlast/EPlast.BLL/DTO/AboutBase/SubsectionDTO.cs
> +
delete spaces

2021-07-22 09:32 UTC, voroniak commented on EPlast/EPlast.BLL/DTO/AboutBase/SubsectionDTO.cs
> +
delete spaces

2021-07-22 09:32 UTC, voroniak commented on EPlast/EPlast.BLL/Interfaces/AboutBase/IAboutBaseSectionService.cs
> +
delete spaces

2021-07-22 09:32 UTC, voroniak commented on EPlast/EPlast.BLL/Mapping/AboutBase/AboutBaseSectionProfile.cs
> +}
format file. crtl r g

2021-07-22 09:32 UTC, voroniak commented on EPlast/EPlast.BLL/Mapping/AboutBase/AboutBaseSubsectionProfile.cs
> +}
format file. crtl r g

2021-07-22 09:32 UTC, voroniak commented on EPlast/EPlast.BLL/Services/AboutBase/AboutBaseSectionService.cs
> +
delete spaces

2021-07-22 09:32 UTC, voroniak commented on EPlast/EPlast.BLL/Services/AboutBase/AboutBaseSubsectionService.cs
> +
delete spaces. The same for other files. Delete unneeded spaces and format files.

2021-07-22 09:32 UTC, voroniak commented on EPlast/EPlast.Tests/Controllers/AboutBaseControllerTests.cs
> +        [Test]
add space. The same for all tests.

2021-07-22 09:32 UTC, voroniak commented on EPlast/EPlast.Tests/Services/AboutBase/SectionServiceTests.cs
> +        };
Could you add "private" to this fields?

2021-07-22 09:32 UTC, voroniak commented on EPlast/EPlast.Tests/Services/AboutBase/SubsectionServiceTests.cs
> +            Assert.AreEqual("Attempted to perform an unauthorized operation.", exception.Message);
You use "Attempted to perform an unauthorized operation." several times. isn't it better to put it in a variable or private field?

2021-07-22 09:32 UTC, voroniak commented on EPlast/EPlast.Tests/Services/AboutBase/SubsectionServiceTests.cs
> +        };
add private

2021-07-22 09:32 UTC, voroniak commented on EPlast/EPlast.WebApi/Controllers/AboutBaseController.cs
> +            }
I don't think that using try catch so many time is ok. don't we have global error handling?

2021-07-22 09:32 UTC, voroniak commented on EPlast/EPlast.WebApi/Mapping/AboutBase/AboutBaseSectionProfile.cs
> +    public class AboutBaseSectionProfile: Profile
Why did you create some Profiles public but the others no?

2021-07-27 12:07 UTC, nicoolle approved these changes

2021-07-27 14:00 UTC, voroniak approved these changes

2021-07-27 14:08 UTC, merged