Fixed adding role "formerUser"
ita-social-projects/EPlast pull request #1517
Opened 2021-07-27 10:31 UTC by nicoolle

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-07-27 10:46 UTC, OleksandrBilan approved these changes

2021-07-27 10:49 UTC, christykobyletska approved these changes

2021-07-29 20:58 UTC, sharix4 requested changes

2021-07-29 20:58 UTC, sharix4 commented on EPlast/EPlast.BLL/Services/Admin/AdminService.cs
> +            await _repoWrapper.SaveAsync();
what is storage for here

2021-08-02 10:13 UTC, sharix4 approved these changes

2021-08-02 11:46 UTC, merged