Fix adding admin with past date
ita-social-projects/EPlast pull request #1525
Opened 2021-07-29 17:25 UTC by OleksandrBilan

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-07-29 19:07 UTC, voroniak requested changes

2021-07-29 19:07 UTC, voroniak commented on EPlast/EPlast.BLL/Services/City/CityParticipantsService.cs
> +        private async Task CheckCityHasAdmin(int cityId, string adminTypeName, CityAdministration newAdmin)
Add Async to the name

2021-07-29 19:16 UTC, OleksandrBilan commented on EPlast/EPlast.BLL/Services/City/CityParticipantsService.cs
> +        private async Task CheckCityHasAdmin(int cityId, string adminTypeName, CityAdministration newAdmin)
Thanks

2021-07-30 13:19 UTC, christykobyletska approved these changes

2021-07-31 21:50 UTC, danylo-melnychuk approved these changes
Good job

2021-08-01 11:41 UTC, voroniak approved these changes

2021-08-01 11:44 UTC, merged