Added IsActive status, Archiving and Unarchiving to Regions, Cities, …
ita-social-projects/EPlast pull request #1527
Opened 2021-07-30 09:07 UTC by andrii52

…Clubs

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-07-30 09:26 UTC, sharix4 requested changes

2021-07-30 09:26 UTC, sharix4 commented on EPlast/EPlast.BLL/Services/City/CityService.cs
> +            var city = await _repoWrapper.City.GetFirstOrDefaultAsync(c => c.ID == cityId && c.IsActive == true);
var city = await _repoWrapper.City.GetFirstOrDefaultAsync(c => c.ID == cityId && c.IsActive);   I think it will be better

2021-07-30 09:26 UTC, sharix4 commented on EPlast/EPlast.BLL/Services/City/CityService.cs
> +            var filteredCities = cities.Where(c => c.IsActive == true);
cities.Where(c => c.IsActive);

2021-07-30 09:26 UTC, sharix4 commented on EPlast/EPlast.BLL/Services/City/CityService.cs
> +            var filteredCities = cities.Where(c => c.IsActive == false);
var filteredCities = cities.Where(c => c.IsActive);

2021-07-30 09:26 UTC, sharix4 commented on EPlast/EPlast.BLL/Services/City/CityService.cs
> +            var city = await _repoWrapper.City.GetFirstOrDefaultAsync(c => c.ID == cityId && c.IsActive == false);
var city = await _repoWrapper.City.GetFirstOrDefaultAsync(c => c.ID == cityId && !c.IsActive);

2021-07-30 09:26 UTC, sharix4 commented on EPlast/EPlast.BLL/Services/Club/ClubService.cs
> +            var club = await _repoWrapper.Club.GetFirstOrDefaultAsync(c => c.ID == clubId && c.IsActive == true);
var club = await _repoWrapper.Club.GetFirstOrDefaultAsync(c => c.ID == clubId && c.IsActive );

2021-07-30 09:26 UTC, sharix4 commented on EPlast/EPlast.BLL/Services/Club/ClubService.cs
> +            var filteredClubs = clubs.Where(c => c.IsActive == false);
var filteredClubs = clubs.Where(c => !c.IsActive);

2021-07-30 09:26 UTC, sharix4 commented on EPlast/EPlast.BLL/Services/Club/ClubService.cs
> +            var filteredClubs = clubs.Where(c => c.IsActive == true);
var filteredClubs = clubs.Where(c => c.IsActive);

2021-07-30 09:26 UTC, sharix4 commented on EPlast/EPlast.BLL/Services/Club/ClubService.cs
> +            var club = await _repoWrapper.Club.GetFirstOrDefaultAsync(c => c.ID == clubId && c.IsActive == false);
var club = await _repoWrapper.Club.GetFirstOrDefaultAsync(c => c.ID == clubId && !c.IsActive);

2021-07-30 09:26 UTC, sharix4 commented on EPlast/EPlast.BLL/Services/Region/RegionService.cs
> +            var region = await _repoWrapper.Region.GetFirstAsync(d => d.ID == regionId && d.IsActive == true);
var region = await _repoWrapper.Region.GetFirstAsync(d => d.ID == regionId && d.IsActive);

2021-07-30 09:26 UTC, sharix4 commented on EPlast/EPlast.BLL/Services/Region/RegionService.cs
> +            var filteredRegions = regions.Where(r => r.Status != RegionsStatusType.RegionBoard && r.IsActive == true);
var filteredRegions = regions.Where(r => r.Status != RegionsStatusType.RegionBoard && r.IsActive);

2021-07-30 09:26 UTC, sharix4 commented on EPlast/EPlast.BLL/Services/Region/RegionService.cs
> +            var filteredRegions = regions.Where(r => r.Status != RegionsStatusType.RegionBoard && r.IsActive == false);
see above

2021-07-30 09:26 UTC, sharix4 commented on EPlast/EPlast.BLL/Services/Region/RegionService.cs
> +                .GetAllAsync()).Where(r => r.Status != RegionsStatusType.RegionBoard && r.IsActive == true));
see above

2021-07-30 09:26 UTC, sharix4 commented on EPlast/EPlast.BLL/Services/Region/RegionService.cs
> +            var region = await _repoWrapper.Region.GetFirstAsync(d => d.ID == regionId && d.IsActive == false);
see above

2021-07-30 09:28 UTC, sharix4 requested changes
Not enough tests

2021-07-30 10:13 UTC, OleksandrBilan commented on EPlast/EPlast.BLL/Services/City/CityService.cs
> +            var filteredCities = cities.Where(c => c.IsActive == false);
с => !c.IsActive

2021-08-01 12:28 UTC, andrii52 commented on EPlast/EPlast.BLL/Services/City/CityService.cs
> +            var filteredCities = cities.Where(c => c.IsActive == false);
Done

2021-08-01 12:28 UTC, andrii52 commented on EPlast/EPlast.BLL/Services/City/CityService.cs
> +            var city = await _repoWrapper.City.GetFirstOrDefaultAsync(c => c.ID == cityId && c.IsActive == true);
Done

2021-08-01 14:52 UTC, christykobyletska requested changes

2021-08-01 14:52 UTC, christykobyletska commented on EPlast/EPlast.Tests/Services/City/CityServiceTests.cs
> +
delete one space

2021-08-01 14:52 UTC, christykobyletska commented on EPlast/EPlast.Tests/Services/City/CityServiceTests.cs
> +
delete one space

2021-08-01 14:52 UTC, christykobyletska commented on EPlast/EPlast.Tests/Services/Regions/RegionServiceTest.cs
> +
delete this space

2021-08-01 14:52 UTC, christykobyletska commented on EPlast/EPlast.Tests/Services/Regions/RegionServiceTest.cs
> +            // Act
and before //act add one space

2021-08-01 14:52 UTC, christykobyletska commented on EPlast/EPlast.Tests/Services/Regions/RegionServiceTest.cs
> +            // Act
in other tests you added spaces between //arrange and //act, //art and //assert blocks. Can you unify to one sample

2021-08-01 14:52 UTC, christykobyletska commented on EPlast/EPlast.Tests/Services/Regions/RegionServiceTest.cs
> +            // Act
and here, read comment above

2021-08-01 14:52 UTC, christykobyletska commented on EPlast/EPlast.Tests/Services/Regions/RegionServiceTest.cs
> +
delete space

2021-08-01 14:52 UTC, christykobyletska commented on EPlast/EPlast.Tests/Services/Regions/RegionServiceTest.cs
> +            // Act
add space before //act

2021-08-01 14:52 UTC, christykobyletska commented on EPlast/EPlast.Tests/Services/Regions/RegionServiceTest.cs
> +
delete s[pace

2021-08-01 14:52 UTC, christykobyletska commented on EPlast/EPlast.Tests/Services/Regions/RegionServiceTest.cs
> +
delete space

2021-08-01 14:52 UTC, christykobyletska commented on EPlast/EPlast.Tests/Services/Regions/RegionServiceTest.cs
> +
delete space

2021-08-01 14:52 UTC, christykobyletska commented on EPlast/EPlast.Tests/Services/Regions/RegionServiceTest.cs
> +
delete space

2021-08-01 14:52 UTC, christykobyletska commented on EPlast/EPlast.Tests/Controllers/RegionsControllerTests.cs
> +            // Act
in other tests you added spaces between //arrange and //act, //art and //assert blocks. Can you unify to one sample

2021-08-01 15:11 UTC, christykobyletska approved these changes

2021-08-01 15:16 UTC, OleksandrBilan approved these changes

2021-08-01 16:19 UTC, voroniak requested changes

2021-08-01 16:19 UTC, voroniak commented on EPlast/EPlast.BLL/Interfaces/City/ICityService.cs
> +        /// Get all active cities
Change from Get to Gets, the same for all others

2021-08-01 16:19 UTC, voroniak commented on EPlast/EPlast.BLL/Interfaces/City/ICityService.cs
> +        Task<IEnumerable<CityDTO>> GetAllNotActiveDTOAsync(string cityName = null);
I think we don't have to use dto in the method name

2021-08-01 16:19 UTC, voroniak commented on EPlast/EPlast.BLL/Interfaces/Club/IClubService.cs
> +        Task<IEnumerable<ClubDTO>> GetAllActiveDTOAsync(string clubName = null);
The same

2021-08-01 16:19 UTC, voroniak commented on EPlast/EPlast.BLL/Services/Region/RegionService.cs
> +        public async Task ArchiveRegion(int regionId)
Add Async

2021-08-01 16:19 UTC, voroniak commented on EPlast/EPlast.BLL/Services/Region/RegionService.cs
> +        public async Task UnArchiveRegion(int regionId)
Add Async

2021-08-01 17:48 UTC, andrii52 commented on EPlast/EPlast.BLL/Interfaces/City/ICityService.cs
> +        /// Get all active cities
Done

2021-08-03 07:42 UTC, voroniak approved these changes

2021-08-03 09:57 UTC, sharix4 approved these changes

2021-08-03 14:37 UTC, merged