Access level
ita-social-projects/EPlast pull request #1587
Opened 2021-08-05 07:56 UTC by nicoolle

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-08-05 08:09 UTC, sharix4 requested changes

2021-08-05 08:09 UTC, sharix4 commented on EPlast/EPlast.BLL/DTO/ActiveMembership/AccessLevelTypeDTO.cs
> +        [Description("Доступ члена проводу організації, Діловод Округи")]
this user does not have access  [Description("Доступ члена проводу організації, Діловод Округи")] It should be   Діловод Округи

2021-08-05 08:14 UTC, nicoolle commented on EPlast/EPlast.BLL/DTO/ActiveMembership/AccessLevelTypeDTO.cs
> +        [Description("Доступ члена проводу організації, Діловод Округи")]
Just for Діловод Округи or and for Діловод Станиці, Діловод Куреня?

2021-08-05 08:16 UTC, sharix4 requested changes

2021-08-05 08:16 UTC, sharix4 commented on EPlast/EPlast.BLL/Services/ActiveMembership/AccessLevelService.cs
> +            if (userRoles.Intersect(leadershipLevelRoleForGoverningBodyHead).Any())
here it is probably necessary switch case

2021-08-05 08:16 UTC, sharix4 commented on EPlast/EPlast.BLL/Services/ActiveMembership/AccessLevelService.cs
> +            var leadershipLevelRoleForSectorHead = new List<string>
why do you have so many lists with 1 value

2021-09-01 12:04 UTC, closed without merging

2021-09-01 12:04 UTC, christykobyletska commented
already done