added-announcement
ita-social-projects/EPlast pull request #1609
Opened 2021-08-10 13:02 UTC by solomiyon

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-08-10 16:26 UTC, sharix4 requested changes

2021-08-10 16:47 UTC, sharix4 requested changes

2021-08-10 16:47 UTC, sharix4 commented on EPlast/EPlast.BLL/Services/GoverningBodies/Announcement/GoverningBodyAnnouncementService.cs
> +            if (text != null)
if (text == null)
            {
return false; 
}

2021-08-10 16:47 UTC, sharix4 commented on EPlast/EPlast.Tests/Controllers/GoverningBodiesControllerTests.cs
> +            //Assert
spaсe

2021-08-10 16:47 UTC, sharix4 commented on EPlast/EPlast.Tests/Services/GoverningBody/Announcement/GoverningBodyAnnouncementServiceTest.cs
> +        //_repoWrapper.User.GetFirstOrDefaultAsync(d => d.Id == announcement.UserId
delete

2021-08-10 19:22 UTC, solomiyon commented on EPlast/EPlast.Tests/Controllers/GoverningBodiesControllerTests.cs
> +        //private GoverningBodyAnnouncementUserDTO CreateGoverningBodyAnnouncementUserDTO => new GoverningBodyAnnouncementUserDTO()
done

2021-08-10 19:22 UTC, solomiyon commented on EPlast/EPlast.BLL/Services/GoverningBodies/Announcement/GoverningBodyAnnouncementService.cs
> +            if (text != null)
but this works in the same way

2021-08-10 19:22 UTC, solomiyon commented on EPlast/EPlast.Tests/Controllers/GoverningBodiesControllerTests.cs
> +            //Assert
done

2021-08-10 19:22 UTC, solomiyon commented on EPlast/EPlast.Tests/Services/GoverningBody/Announcement/GoverningBodyAnnouncementServiceTest.cs
> +        //_repoWrapper.User.GetFirstOrDefaultAsync(d => d.Id == announcement.UserId
done

2021-08-10 19:22 UTC, solomiyon commented on EPlast/EPlast.BLL/Interfaces/GoverningBodies/Announcement/IGoverningBodyAnnouncementService.cs
> +        Task DeleteAnnouncement(int id);
done

2021-08-10 19:22 UTC, solomiyon commented on EPlast/EPlast.BLL/Interfaces/GoverningBodies/Announcement/IGoverningBodyAnnouncementService.cs
> +        Task<bool> AddAnnouncement(string text);
done

2021-08-10 19:22 UTC, solomiyon commented on EPlast/EPlast.BLL/Interfaces/GoverningBodies/Announcement/IGoverningBodyAnnouncementService.cs
> +        Task<GoverningBodyAnnouncementUserDTO> GetAnnouncementById(int id);
done

2021-08-10 20:07 UTC, danylo-melnychuk commented on EPlast/EPlast.Tests/Services/GoverningBody/Announcement/GoverningBodyAnnouncementServiceTest.cs
> +            Assert.IsNotNull(result);
Probably, we also have to Assert.Equal().
What do you think Solomiya?

2021-08-10 20:07 UTC, danylo-melnychuk commented on EPlast/EPlast.WebApi/Controllers/GoverningBodiesController.cs
> +                return NoContent();
Are you sure that we have to use status code 204 either 200?

2021-08-12 12:26 UTC, ostappppppp commented on EPlast/EPlast.BLL/Services/GoverningBodies/Announcement/GoverningBodyAnnouncementService.cs
> +                return true;
if I`m not mistaken, we separate `return` statement with empty line in whole project
it's used for better reading experience

2021-08-12 12:29 UTC, ostappppppp commented on EPlast/EPlast.WebApi/Controllers/GoverningBodiesController.cs
> +                return NoContent();
+1
204 used for deletion operations

2021-08-15 08:06 UTC, solomiyon commented on EPlast/EPlast.BLL/Services/GoverningBodies/Announcement/GoverningBodyAnnouncementService.cs
> +                return true;
fixed

2021-08-15 08:06 UTC, solomiyon commented on EPlast/EPlast.WebApi/Controllers/GoverningBodiesController.cs
> +                return NoContent();
fixed

2021-08-15 08:06 UTC, solomiyon commented on EPlast/EPlast.Tests/Services/GoverningBody/Announcement/GoverningBodyAnnouncementServiceTest.cs
> +            Assert.IsNotNull(result);
added more asserts

2021-08-15 10:21 UTC, OleksandrBilan approved these changes

2021-08-15 16:31 UTC, christykobyletska approved these changes

2021-08-15 17:19 UTC, nicoolle approved these changes

2021-08-15 19:18 UTC, sharix4 requested changes

2021-08-16 07:45 UTC, ostappppppp approved these changes

2021-08-16 07:54 UTC, solomiyon commented on EPlast/EPlast.BLL/Services/GoverningBodies/Announcement/GoverningBodyAnnouncementService.cs
> +            if (text != null)
fixed

2021-08-16 07:57 UTC, sharix4 approved these changes

2021-08-16 08:38 UTC, merged