Added check for former member when login in
ita-social-projects/EPlast pull request #1725
Opened 2021-09-05 20:46 UTC by Tali32

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-09-07 08:05 UTC, OleksandrBilan commented on EPlast/EPlast.Tests/Controllers/LoginControllerTests.cs
> +            Assert.AreEqual(GetLoginUserFormerMember().ToString(), result.Value.ToString());
if 'result' is null, you will get the NullReferenceException when trying to get the 'Value', so place this Assert method as the last in the test

2021-09-07 08:05 UTC, OleksandrBilan commented on EPlast/EPlast.Tests/Controllers/LoginControllerTests.cs
> +            mockResources.Verify();
I think it's better to verify the exact methods that are called from the mocked objects and not the objects themselves

2021-09-07 08:05 UTC, OleksandrBilan commented on EPlast/EPlast.Tests/Controllers/LoginControllerTests.cs
> +        public async Task Test_LoginPost_UserFormerMember()
The name doesn't comply with the rules of naming test methods

2021-09-07 08:05 UTC, OleksandrBilan commented on EPlast/EPlast.Tests/Controllers/LoginControllerTests.cs
> +            Assert.NotNull(result);
same as in the previous test

2021-09-07 09:30 UTC, Tali32 commented on EPlast/EPlast.Tests/Controllers/LoginControllerTests.cs
> +            Assert.AreEqual(GetLoginUserFormerMember().ToString(), result.Value.ToString());
Done!

2021-09-07 09:30 UTC, Tali32 commented on EPlast/EPlast.Tests/Controllers/LoginControllerTests.cs
> +            mockResources.Verify();
Done!

2021-09-07 09:30 UTC, Tali32 commented on EPlast/EPlast.Tests/Controllers/LoginControllerTests.cs
> +        public async Task Test_LoginPost_UserFormerMember()
Fixed!

2021-09-07 09:31 UTC, Tali32 commented on EPlast/EPlast.Tests/Controllers/LoginControllerTests.cs
> +            Assert.NotNull(result);
Done!

2021-09-07 14:50 UTC, OleksandrBilan approved these changes

2021-09-08 09:49 UTC, nicoolle approved these changes

2021-09-08 10:01 UTC, christykobyletska requested changes

2021-09-08 10:01 UTC, christykobyletska commented on EPlast/EPlast.Tests/Controllers/LoginControllerTests.cs
> +                loginController) = CreateLoginController();
Can you place this in SetUp, it seems to me you use it in a few tests?

2021-09-08 10:38 UTC, Tali32 commented on EPlast/EPlast.Tests/Controllers/LoginControllerTests.cs
> +                loginController) = CreateLoginController();
It uses at few tests because we use the methood "CreateLoginController" which returns us only needed exactlyat this Test prepeared fields

2021-09-08 10:43 UTC, christykobyletska commented on EPlast/EPlast.Tests/Controllers/LoginControllerTests.cs
> +                loginController) = CreateLoginController();
yep

2021-09-08 10:43 UTC, christykobyletska approved these changes

2021-09-08 16:22 UTC, merged