Added tests for DecisionsService, GoverningBodyAnnouncementService an…
ita-social-projects/EPlast pull request #1763
Opened 2021-09-09 19:10 UTC by VolodymyrKostiv

…d PDFService

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-09-10 15:31 UTC, juliazhorniakAMI approved these changes

2021-09-11 14:40 UTC, OleksandrBilan requested changes

2021-09-11 14:40 UTC, OleksandrBilan commented on EPlast/EPlast.Tests/Services/GoverningBody/Announcement/GoverningBodyAnnouncementServiceTest.cs
> +            Assert.IsNotNull(result);
return value can not be null, so there is no need check for it

2021-09-11 14:40 UTC, OleksandrBilan commented on EPlast/EPlast.Tests/Services/GoverningBody/Announcement/GoverningBodyAnnouncementServiceTest.cs
> +            Assert.IsNotNull(result);
the same here

2021-09-11 14:40 UTC, OleksandrBilan commented on EPlast/EPlast.Tests/Services/GoverningBody/Announcement/GoverningBodyAnnouncementServiceTest.cs
> +            _repoWrapper.Verify(x => x.GoverningBodyAnnouncement.CreateAsync(It.IsAny<GoverningBodyAnnouncement>()));
it would be better to create local variable for GoverningBodyAnnouncement and check if this method takes exactly this variable

2021-09-11 14:40 UTC, OleksandrBilan commented on EPlast/EPlast.Tests/Services/PDF/PDFServiceTests.cs
> +            _repository.Verify(rep => rep.Decesion.GetFirstAsync(It.IsAny<Expression<Func<Decesion, bool>>>(),
there is no need to check mocked method

2021-09-11 14:40 UTC, OleksandrBilan commented on EPlast/EPlast.Tests/Services/PDF/PDFServiceTests.cs
> +            var methodicDocumentRepository = new Mock<IMethodicDocumentRepository>();
delete unused variable

2021-09-11 15:34 UTC, OleksandrBilan approved these changes
Nice!

2021-09-11 15:56 UTC, DmytroZelinsky approved these changes

2021-09-11 15:56 UTC, merged