Bodasyuk
ita-social-projects/EPlast pull request #1789
Opened 2021-09-14 13:19 UTC by Bodasyuk

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-09-14 13:36 UTC, VolodymyrKostiv requested changes

2021-09-14 13:36 UTC, VolodymyrKostiv commented on EPlast/EPlast.Tests/Controllers/ClubControllerTests.cs
> +        {
Method name doesn't comply with test method naming convention

2021-09-14 13:36 UTC, VolodymyrKostiv commented on EPlast/EPlast.WebApi/appsettings.json
> +    "Issuer": "https://localhost:5000/",
Change port to previous

2021-09-14 14:08 UTC, ostappppppp commented
**FYI:**
Name of PR should mean something, but not just some random words or just your username

2021-09-17 11:32 UTC, nicoolle approved these changes

2021-09-17 12:22 UTC, VolodymyrKostiv reviewed
Fix code smells

2021-09-23 08:09 UTC, VolodymyrKostiv approved these changes

2021-09-27 09:39 UTC, OleksandrBilan commented on EPlast/EPlast.Tests/Services/UserProfiles/UserServiceTests.cs
> +            _focusUser.Object.ClubMembers = new List<ClubMembers>() { new ClubMembers() { Club = new DataAccess.Entities.Club(), UserId = "1" }, };
You have the same initialization in the previous test, so it would be better to create some methods (or properties), which will return this initialized objects in one place, and use them in each test

2021-09-27 18:45 UTC, sharix4 approved these changes

2021-09-27 20:24 UTC, merged