Restricted possibility to edit profiles via API (Fixed issue #1825)
ita-social-projects/EPlast pull request #1839
Opened 2021-09-28 17:14 UTC by petromonka

dev
## JIRA
 
* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-09-29 14:34 UTC, sharix4 approved these changes

2021-09-29 16:15 UTC, christykobyletska requested changes

2021-09-29 16:15 UTC, christykobyletska commented on EPlast/EPlast.Tests/Controllers/UserControllerTests.cs
> +            // Assert
Arrange

2021-09-29 16:15 UTC, christykobyletska commented on EPlast/EPlast.Tests/Controllers/UserControllerTests.cs
> +            // Assert
please add empty line before assert block

2021-09-29 16:15 UTC, christykobyletska commented on EPlast/EPlast.Tests/Controllers/UserControllerTests.cs
> +            // Assert
this block should be named arrange

2021-09-29 16:15 UTC, christykobyletska commented on EPlast/EPlast.Tests/Controllers/UserControllerTests.cs
> +
please delete this unnecessary added empty line

2021-09-30 07:40 UTC, christykobyletska commented on EPlast/EPlast.Tests/Controllers/UserControllerTests.cs
>              // Assert
please, change also here to arrange, and look through all test in this file, somewhere could be same situation

2021-09-30 08:01 UTC, christykobyletska approved these changes

2021-09-30 12:58 UTC, OleksandrBilan approved these changes

2021-10-01 07:39 UTC, merged