The system keeps previously got titles in region even after users joining to another city or region
ita-social-projects/EPlast pull request #1841
Opened 2021-09-29 09:45 UTC by Bodasyuk

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-09-29 09:50 UTC, OleksandrBilan approved these changes

2021-09-29 09:51 UTC, nicoolle approved these changes

2021-09-29 13:15 UTC, christykobyletska approved these changes

2021-09-29 14:32 UTC, sharix4 requested changes

2021-09-29 14:32 UTC, sharix4 commented on EPlast/EPlast.BLL/Services/City/CityParticipantsService.cs
> +            var regId = _cityService.GetByIdAsync(cityId).Result.RegionId;
await _cityService If I'm not mistaken

2021-09-29 19:51 UTC, Bodasyuk commented on EPlast/EPlast.BLL/Services/City/CityParticipantsService.cs
> +            var regId = _cityService.GetByIdAsync(cityId).Result.RegionId;
![image](https://user-images.githubusercontent.com/49231163/135338727-36cc755c-c584-4bab-92a4-90e9544339b1.png)

2021-09-30 04:56 UTC, petromonka approved these changes

2021-09-30 09:41 UTC, sharix4 requested changes

2021-09-30 09:50 UTC, Bodasyuk commented on EPlast/EPlast.BLL/Services/City/CityParticipantsService.cs
> +            var regId = _cityService.GetByIdAsync(cityId).Result.RegionId;
changed

2021-09-30 10:18 UTC, sharix4 approved these changes

2021-09-30 10:19 UTC, merged

2021-09-30 10:36 UTC, ostappppppp commented on EPlast/EPlast.BLL/Services/City/CityParticipantsService.cs
> +            var regId = await _cityService.GetByIdAsync(cityId);
Is it `regId` supposed to be `regionId`?
If yes, then I guess my option quite better

2021-09-30 10:36 UTC, ostappppppp commented on EPlast/EPlast.BLL/Services/Region/RegionAdministrationService.cs
> +
Do you need here this empty space?

2021-09-30 10:36 UTC, ostappppppp commented on EPlast/EPlast.Tests/Services/City/CityParticipantsServiceTests.cs
> +            var result = await _cityParticipantsService.AddFollowerAsync(It.IsAny<int>(), "1");
Please, avoid using magic numbers

2021-09-30 10:36 UTC, ostappppppp commented on EPlast/EPlast.WebApi/Controllers/UserController.cs
> +
also empty line here

2021-09-30 11:07 UTC, Bodasyuk commented on EPlast/EPlast.BLL/Services/City/CityParticipantsService.cs
> +            var regId = await _cityService.GetByIdAsync(cityId);
Ok, thanks

2021-09-30 11:07 UTC, Bodasyuk commented on EPlast/EPlast.BLL/Services/Region/RegionAdministrationService.cs
> +
No, thanks

2021-09-30 11:08 UTC, Bodasyuk commented on EPlast/EPlast.WebApi/Controllers/UserController.cs
> +
thanks

2021-09-30 11:11 UTC, Bodasyuk commented on EPlast/EPlast.Tests/Services/City/CityParticipantsServiceTests.cs
> +            var result = await _cityParticipantsService.AddFollowerAsync(It.IsAny<int>(), "1");
Ok, thaks