fix for PDF
ita-social-projects/EPlast pull request #2004
Opened 2021-11-03 17:38 UTC by VSBalanchuk

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-11-03 17:44 UTC, Bodasyuk commented on EPlast/EPlast.BLL/Services/PDF/Documents/AnnualReportPdf.cs
> +
Remove white space

2021-11-03 17:44 UTC, Bodasyuk commented on EPlast/EPlast.BLL/Services/PDF/Documents/AnnualReportPdf.cs
> +            tf.DrawString((_annualReport.ListProperty != null ? $"{_annualReport.ListProperty}" : "Інформація відсутня"), font, XBrushes.Black, textArea, XStringFormats.TopLeft);
We need this white space?

2021-11-03 17:45 UTC, Bodasyuk commented on EPlast/EPlast.BLL/Services/PDF/Documents/AnnualReportPdf.cs
> +            tf.DrawString((_annualReport.ListProperty != null ? $"{_annualReport.ListProperty}" : "Інформація відсутня"), font, XBrushes.Black, textArea, XStringFormats.TopLeft);
(Line 210)

2021-11-03 17:52 UTC, Bodasyuk approved these changes

2021-11-03 17:52 UTC, VSBalanchuk commented on EPlast/EPlast.BLL/Services/PDF/Documents/AnnualReportPdf.cs
> +
Changed

2021-11-03 17:52 UTC, VSBalanchuk commented on EPlast/EPlast.BLL/Services/PDF/Documents/AnnualReportPdf.cs
> +            tf.DrawString((_annualReport.ListProperty != null ? $"{_annualReport.ListProperty}" : "Інформація відсутня"), font, XBrushes.Black, textArea, XStringFormats.TopLeft);
Changed

2021-11-03 17:53 UTC, christykobyletska approved these changes

2021-11-03 17:53 UTC, YuriiDzioba approved these changes

2021-11-03 18:02 UTC, Bodasyuk requested changes

2021-11-03 18:02 UTC, Bodasyuk commented on EPlast/EPlast.BLL/Services/PDF/Documents/AnnualReportPdf.cs
> +                : (_annualReport.ImprovementNeeds.Split('\n').Length - 1) * 10;
Remove magic numbers

2021-11-03 18:05 UTC, Bodasyuk commented on EPlast/EPlast.BLL/Services/PDF/Documents/AnnualReportPdf.cs
>              // Also missing:
What is gfx?

2021-11-03 18:06 UTC, Bodasyuk commented on EPlast/EPlast.BLL/Services/PDF/Documents/AnnualReportPdf.cs
> +        private const int BaseFontSize = 10;
Add enter pls

2021-11-03 18:08 UTC, VSBalanchuk commented on EPlast/EPlast.BLL/Services/PDF/Documents/AnnualReportPdf.cs
>              // Also missing:
![image](https://user-images.githubusercontent.com/46971722/140167565-53909cdf-fa0f-4e4c-aac8-a3342325f2e0.png)
This naming is used in official documentation

2021-11-03 18:17 UTC, VSBalanchuk commented on EPlast/EPlast.BLL/Services/PDF/Documents/AnnualReportPdf.cs
> +        private const int BaseFontSize = 10;
Changed

2021-11-03 20:25 UTC, sharix4 approved these changes

2021-11-07 13:37 UTC, VSBalanchuk commented on EPlast/EPlast.BLL/Services/PDF/Documents/AnnualReportPdf.cs
> +                : (_annualReport.ImprovementNeeds.Split('\n').Length - 1) * 10;
changed

2021-11-07 14:49 UTC, Bodasyuk approved these changes

2021-11-07 14:50 UTC, merged