Fixed user profile access at blanks page (Fixed issues #2195 #2194 #2196)
ita-social-projects/EPlast pull request #2251
Opened 2022-01-05 10:45 UTC by petromonka

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2022-01-05 19:24 UTC, sharix4 requested changes
TESTS

2022-01-08 11:47 UTC, IlliaDR approved these changes

2022-01-10 11:07 UTC, 0l9h approved these changes

2022-01-11 19:11 UTC, OleksandrBilan commented on EPlast/EPlast.BLL/Interfaces/UserProfiles/IUserService.cs
> +        Task<bool> IsUserInSameCell(UserDTO currentUser, UserDTO focusUser, CellType cellType);
IsUserInSameCellAsync*

2022-01-11 19:11 UTC, OleksandrBilan commented on EPlast/EPlast.BLL/Interfaces/UserProfiles/IUserService.cs
> +        /// <returns></returns>
remove useless line

2022-01-12 13:08 UTC, danylo-melnychuk approved these changes

2022-01-12 13:42 UTC, petromonka commented on EPlast/EPlast.BLL/Interfaces/UserProfiles/IUserService.cs
> +        Task<bool> IsUserInSameCell(UserDTO currentUser, UserDTO focusUser, CellType cellType);
I always forget to add this suffix. Thank you for remind 👍

2022-01-12 22:00 UTC, petromonka commented
> TESTS

Tests✅ are added, so please approve this PR... 
Thank you in advance 👍

2022-01-13 13:06 UTC, sharix4 approved these changes

2022-01-13 13:30 UTC, merged