Bug/2201 not list previously roles
ita-social-projects/EPlast pull request #2366
Opened 2022-03-02 10:52 UTC by Goven112

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2022-03-03 11:32 UTC, DimaDiD approved these changes

2022-03-05 15:39 UTC, VSBalanchuk requested changes
There are a lot of missing or extra empty lines. 
Please format your code at least in one style. 
It will improve readability of your code a lot.

2022-03-05 15:44 UTC, VSBalanchuk commented on EPlast/EPlast.BLL/Interfaces/Region/IRegionAdministrationService.cs
> +        Task EditStatusAdministration(int adminId, bool status = false);
For example here.

2022-03-05 15:44 UTC, VSBalanchuk commented on EPlast/EPlast.Tests/Controllers/RegionsControllerTests.cs
> +        [Test]
Here

2022-03-05 15:44 UTC, VSBalanchuk commented on EPlast/EPlast.Tests/Controllers/RegionsControllerTests.cs
> +        [Test]
Here

2022-03-05 15:45 UTC, VSBalanchuk commented on EPlast/EPlast.Tests/Services/Regions/RegionAdministrationServiceTests.cs
>          public async Task GetAdministrationAsync_ReturnsIEnumerableRegionAdministrationDTO()
Here

2022-03-05 15:46 UTC, VSBalanchuk commented on EPlast/EPlast.Tests/Services/Regions/RegionAdministrationServiceTests.cs
>          private static AdminTypeDTO AdminTypeHead = new AdminTypeDTO
Here

2022-03-05 15:46 UTC, VSBalanchuk commented on EPlast/EPlast.WebApi/Controllers/RegionsController.cs
> +        [HttpPut("ChangeStatusAdministration/{Id}")]
Here

2022-03-05 15:53 UTC, VSBalanchuk reviewed
Try out auto formatting. 
For example, you can use: 
- ReSharper feature named "Cleanup code" 
- I think even ctrl+k => ctrl+f will help you a lot

2022-03-23 13:39 UTC, Goven112 commented on EPlast/EPlast.Tests/Services/Regions/RegionAdministrationServiceTests.cs
>          private static AdminTypeDTO AdminTypeHead = new AdminTypeDTO
done

2022-03-23 20:18 UTC, VSBalanchuk commented on EPlast/EPlast.BLL/Services/Region/RegionAdministrationService.cs
> -
Revert this change.

2022-03-23 20:28 UTC, VSBalanchuk commented on EPlast/EPlast.BLL/Services/Region/RegionAdministrationService.cs
>          public async Task DeleteAdminByIdAsync(int Id)
Add empty line

2022-03-23 20:42 UTC, VSBalanchuk approved these changes

2022-03-23 21:22 UTC, merged