Bug/2291 repository add doc
ita-social-projects/EPlast pull request #2379
Opened 2022-03-28 23:00 UTC by Goven112

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2022-03-30 18:50 UTC, bkondrat requested changes

2022-03-30 18:50 UTC, bkondrat commented on EPlast/EPlast.Resources/Roles.cs
> +        public const string AdminAndAdminsOfOkrugaAndKrayuAndCityAndKurin = Admin+"," + OkrugaHead+","+RegionBoardHead+","+CityHead+","+KurinHead;
please add spices between phrases and symbols

2022-03-31 00:28 UTC, Goven112 commented on EPlast/EPlast.Resources/Roles.cs
> +        public const string AdminAndAdminsOfOkrugaAndKrayuAndCityAndKurin = Admin+"," + OkrugaHead+","+RegionBoardHead+","+CityHead+","+KurinHead;
thanks done

2022-03-31 08:10 UTC, bkondrat approved these changes

2022-03-31 08:10 UTC, bkondrat commented on EPlast/EPlast.Resources/Roles.cs
> +        public const string AdminAndAdminsOfOkrugaAndKrayuAndCityAndKurin = Admin+"," + OkrugaHead+","+RegionBoardHead+","+CityHead+","+KurinHead;
great 🙌

2022-03-31 08:12 UTC, Omeliukh-Nazar approved these changes

2022-03-31 17:41 UTC, VSBalanchuk approved these changes

2022-03-31 17:55 UTC, merged