Add VSCode IDE configuration
ita-social-projects/EPlast pull request #2428
Opened 2022-05-16 18:42 UTC by tvardero

**Important.**
This PR does not affect project in any way.
It only enables launch profiles to use in VS Code IDE.

## Code reviewers

- [ ] ?

### Second Level Review

- [ ] @Goven112
- [ ] @bkondrat
- [ ] @Omeliukh-Nazar

## Summary of issue

Some users (like me) have performance issues using VS Community 2022 due to old PC configuration or running the project on not high-end laptop. So lightweight IDE is a good option for them. For example VS Code, which is also used on our EPlast-Client project as main IDE.

Currently VS Code is not configured to build, watch nor launch the project. This PR addresses that.

## Summary of change

- Added `tasks.json` configuration to build the project (works like `dotnet build --project ./EPlast/EPlast.WebApi/`)
- Added `tasks.json` configuration to watch the project (works like `dotnet watch run --project ./EPlast/EPlast.WebApi/ --urls ...`)
- Added `launch.json` configuration to run project (pre-launch task `build`, then `dotnet run --urls ...`)
- Added `extensions.json` file with recommended VS Code extensions to use with this project
- Added `settings.json` to set up best-fitted VS Code extensions settings and VS Code IDE settings
- Updated `.gitignore` to exclude any other content in `.vscode/` folder (like some extensions cache, etc.)

## Testing approach

PR does not affect the project, no testing required.

## How to use VS Code to develop and debug EPlast backend project

User manual (temporarily in russian language, sorry for that): [Google Drive](https://drive.google.com/file/d/1sUPiNapVc3DHzLqrs3_zTQkPyUUFcA6g/view?usp=sharing).

Переклад на українську мову буде зроблено незабаром, та інструкція (після аппруву) буде додана до Вікі цього репозиторію.

## CHECK LIST

- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  PR meets all conventions

2022-05-17 07:01 UTC, Omeliukh-Nazar approved these changes

2022-05-18 10:36 UTC, tvardero commented
Переклад інструкції на українську зроблено.

2022-05-20 08:17 UTC, ostappppppp requested changes

2022-05-20 08:17 UTC, ostappppppp commented on .vscode/settings.json
> +    "ru": true,
do we need `ru` locale? I assume we don't

2022-05-20 08:29 UTC, tvardero commented on .vscode/settings.json
> +    "ru": true,
It is used to disable VS Code warning of Cyrillic Unicode being simillar to latine Unicode characters

For example 'Т' in word "Тест" (writter in ukrainian keyboard layout or russian - doesn't matter) will be highlighted by VS Code because this charracter might be confused with 'T' in english keyboard layout. 
Ukraininan keyboard layout mostly reuses characters from russian keyboard layout.

This setting disables VS Code warning.

2022-05-20 08:30 UTC, tvardero commented on .vscode/settings.json
> +    "ru": true,
![image](https://user-images.githubusercontent.com/45442278/169487907-47feea0d-c325-4171-a5d2-12c72c19ddb4.png)

2022-05-20 08:37 UTC, ostappppppp commented on .vscode/settings.json
> +    "ru": true,
do we have intention to write something in russian keyboard in code?
if not, `ua` locale should be enough

2022-05-20 08:44 UTC, tvardero commented on .vscode/settings.json
> +    "ru": true,
It won't solve the issue because most of ukrainian letters use 'ru' locale: 
![image](https://user-images.githubusercontent.com/45442278/169490254-845ec04e-d210-484c-ac0c-d5397abab6e2.png)

Still getting warnings if "ru" locale is not selected.

The string was written in ukrainian keyboard layout

2022-05-20 08:44 UTC, ostappppppp commented on .vscode/settings.json
> +    "ru": true,
also I found this option, you need to uncheck it(didn't check if it's work)
<img width="543" alt="image" src="https://user-images.githubusercontent.com/9966691/169490516-f3a42ad3-8c9c-41ab-98de-8ff1dd35d780.png">

2022-05-20 08:50 UTC, ostappppppp commented
Just one common question, does anyone else from your team will be using VS Code as IDE for .NET?

2022-05-20 08:56 UTC, ostappppppp commented
Just one common question, does anyone else from your team will be using VS Code as IDE for .NET?

2022-05-20 09:06 UTC, tvardero commented
> Just one common question, does anyone else from your team will be using VS Code as IDE for .NET?

Currently I'm the one who use VS Code for backend, but Grigory (from my team) might also switch to VS Code because he has big performance issues running both Zoom and VS Community together.

2022-05-20 09:14 UTC, ostappppppp commented
> > Just one common question, does anyone else from your team will be using VS Code as IDE for .NET?
> 
> Currently I'm the one who use VS Code for backend, but Grigory (from my team) might also switch to VS Code because he has big performance issues running both Zoom and VS Community together.

maybe if it's only you two for now it worth to have that config locally, because I don't think it become common thing to use VS Code for .NET on Eplast

2022-05-20 09:36 UTC, tvardero commented on .vscode/settings.json
> +    "ru": true,
Might work

2022-05-20 10:03 UTC, tvardero commented
> maybe if it's only you two for now it worth to have that config locally, because I don't think it become common thing to use VS Code for .NET on Eplast

VS Community doesn't need to be configured (as i see) to launch this project out-of-box. VS Code does.

If this PR gets blocked, people in future (after my group graduation) will have to do all this configuration from scratch for themself. Or run the project in a terminal, which is _very very bad_ for debugging as there is no IDE problem matching from terminal. 

As alternative, we could zip those changes and store them on Google Drive of the project. And just add `.vscode/` folder in `.gitignore`. However the zip won't be updated that easily there, like on git.

2022-05-20 10:27 UTC, ostappppppp commented
> > maybe if it's only you two for now it worth to have that config locally, because I don't think it become common thing to use VS Code for .NET on Eplast
> 
> VS Community doesn't need to be configured (as i see) to launch this project out-of-box. VS Code does.
> 
> If this PR gets blocked, people in future (after my group graduation) will have to do all this configuration from scratch for themself. Or run the project in a terminal, which is _very very bad_ for debugging as there is no IDE problem matching from terminal.
> 
> As alternative, we could zip those changes and store them on Google Drive of the project. And just add `.vscode/` folder in `.gitignore`. However the zip won't be updated that easily there, like on git.

Not a good point, if someone after your graduation, will be using WebStorm or any other IDE it become useless, so I'd propose to add that config to zip and write some `How to` article and how to use it

2022-05-20 12:34 UTC, closed without merging