Present status participants
ita-social-projects/EPlast pull request #2538
Opened 2022-06-03 11:59 UTC by Tomash-Klaus

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2022-06-03 15:27 UTC, tvardero commented on EPlast/EPlast.DataAccess/Migrations/20220601164936_wasPresent_property_for_participant.cs
> +        }
Unnecessary migration

2022-06-03 15:28 UTC, tvardero commented on EPlast/EPlast.DataAccess/Migrations/20220601164936_wasPresent_property_for_participant.cs
> +
Something not ok with this migration, column "WasPresent" is not generated.

2022-06-03 15:28 UTC, tvardero commented on EPlast/EPlast.DataAccess/Migrations/EPlastDBContextModelSnapshot.cs
> +                        .HasColumnType("bit");
No need, EF does it automatically

2022-06-03 15:30 UTC, tvardero commented on EPlast/EPlast.BLL/Services/Events/ParticipantManager.cs
> +            return StatusCodes.Status204NoContent;
Return is not used

2022-06-03 15:32 UTC, tvardero commented on EPlast/EPlast.BLL/Interfaces/Events/IParticipantManager.cs
> -        /// <response code="204">No content</response>
Why?

2022-06-06 08:35 UTC, tvardero commented on EPlast/EPlast.WebApi/Controllers/EventsUsersController.cs
> +            // �� ��� �������� 404 ���� � ���� �� ��������� �� ��������� ����� � ���� �� ��������� � ������
![image](https://user-images.githubusercontent.com/45442278/172125874-4161518c-7a23-4da5-9d56-8bcf6f372039.png)

2022-06-06 08:35 UTC, tvardero commented on EPlast/EPlast.WebApi/Controllers/EventsUsersController.cs
> +        //[HttpPost]
Delete this comment and empty line

2022-06-06 08:35 UTC, tvardero commented on EPlast/EPlast.WebApi/Controllers/EventsUsersController.cs
> +        //[HttpPut]
Delete comment

2022-06-06 08:35 UTC, tvardero commented on EPlast/EPlast.WebApi/Controllers/EventsUsersController.cs
> +            // �� ������ ����� �������� ��� ������ 404 � 400
![image](https://user-images.githubusercontent.com/45442278/172126070-c59d8937-cb2d-42ea-9535-3dea4392b4c7.png)

2022-06-06 08:36 UTC, tvardero requested changes
Read comments

2022-06-13 08:12 UTC, tvardero commented on EPlast/EPlast.BLL/Interfaces/Events/IParticipantManager.cs
> +        Task ChangeUserPresentStatus(int perticipantId);
`ChangeUserPresentStatus` -> `ChangeUserPresentStatusAsync`

2022-06-15 11:50 UTC, tvardero commented on EPlast/EPlast.BLL/Services/Events/ParticipantManager.cs
> +                              .GetFirstAsync(predicate: p => p.ID == id);
GetFirstOrDefaultAsync()
if (part == null) throw KeyNotFoundException()

2022-06-15 12:06 UTC, Tomash-Klaus commented on EPlast/EPlast.BLL/Interfaces/Events/IParticipantManager.cs
> +        Task ChangeUserPresentStatus(int perticipantId);
changed all names

2022-06-15 12:09 UTC, Tomash-Klaus commented on EPlast/EPlast.BLL/Services/Events/ParticipantManager.cs
> +                              .GetFirstAsync(predicate: p => p.ID == id);
done

2022-06-15 12:09 UTC, Tomash-Klaus commented on EPlast/EPlast.WebApi/Controllers/EventsUsersController.cs
> +        //[HttpPatch("{eventId}")] new ????????
done

2022-06-15 12:09 UTC, Tomash-Klaus commented on EPlast/EPlast.WebApi/Controllers/EventsUsersController.cs
> +        //[HttpPut]
done

2022-06-15 12:09 UTC, Tomash-Klaus commented on EPlast/EPlast.WebApi/Controllers/EventsUsersController.cs
> +        //[HttpPost]
done

2022-06-15 12:19 UTC, tvardero approved these changes

2022-06-15 12:21 UTC, bkondrat approved these changes

2022-06-15 12:22 UTC, Omeliukh-Nazar approved these changes

2022-06-15 12:26 UTC, merged