Fix field validation for Cities and Regions on backend 1538
ita-social-projects/EPlast pull request #2572
Opened 2022-06-22 21:12 UTC by vsynieok

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2022-06-22 21:20 UTC, Omeliukh-Nazar approved these changes

2022-06-23 06:35 UTC, hryhoriivoloshyn approved these changes

2022-06-23 07:31 UTC, bkondrat approved these changes

2022-06-23 07:41 UTC, tvardero requested changes
Reviewing

2022-06-23 07:50 UTC, tvardero requested changes

2022-06-23 07:50 UTC, tvardero commented on EPlast/EPlast.BLL/DTO/Region/RegionDTO.cs
> +        [Required, MaxLength(18, ErrorMessage = "Контактний номер округи не може перевищувати 12 символів.")]
Add `[Phone]` attribute to validate that phone format is correct

2022-06-23 07:50 UTC, tvardero commented on EPlast/EPlast.BLL/DTO/Region/RegionDTO.cs
> +        [Required, MaxLength(50, ErrorMessage = "Електронна адреса округи не може перевищувати 50 символів.")]
Add `[EmailAddress]` attribute to validate that email format is correct

2022-06-23 07:50 UTC, tvardero commented on EPlast/EPlast.WebApi/Models/City/CityViewModel.cs
>          public string PhoneNumber { get; set; }
`[Phone]`

2022-06-23 07:50 UTC, tvardero commented on EPlast/EPlast.WebApi/Models/City/CityViewModel.cs
>          public string Email { get; set; }
`[EmailAddress]`

2022-06-23 07:50 UTC, tvardero commented on EPlast/EPlast.WebApi/Models/City/CityViewModel.cs
> +        [MaxLength(256, ErrorMessage = "Посилання на web-сторінку станиці не має перевищувати 256 символів")]
Remove 256 cap.
Add `[Url]` attribute to validate that Url format is correct.

2022-06-23 07:50 UTC, tvardero commented on EPlast/EPlast.WebApi/Models/Club/ClubViewModel.cs
> +        [MaxLength(18, ErrorMessage = "Контактний телефон куреня не може бути довшим за 12 символів.")]
`[Phone]`

2022-06-23 07:50 UTC, tvardero commented on EPlast/EPlast.WebApi/Models/Club/ClubViewModel.cs
>          public string Email { get; set; }
`[EmailAddress]`

2022-06-23 07:50 UTC, tvardero commented on EPlast/EPlast.BLL/DTO/Region/RegionDTO.cs
> +        [Required, MaxLength(50, ErrorMessage = "Назва округи не має перевищувати 50 символів.")]
ErrorMessage:
a) Should not be in any language except for English.
b) Is not used with WebAPI, used only with MVC projects.

Remove all ErrorMessage in every attribute, they are not being used by frontend. ASP.NET will provide default messages in English.

2022-06-23 12:00 UTC, merged