Area entity service controller tests
ita-social-projects/EPlast pull request #2574
Opened 2022-06-23 00:15 UTC by Serhii-Buniak

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2022-06-23 06:20 UTC, hryhoriivoloshyn commented on EPlast/EPlast.DataAccess/EPlast.DataAccess.csproj
> +    <Compile Remove="Migrations\20220622205951_AreaMigration.Designer.cs" />
Changes in this file should be removed. As far as I understand they do not affect migrations in any way, so it's just unnecessary clutter.

2022-06-23 06:20 UTC, hryhoriivoloshyn commented on EPlast/EPlast.DataAccess/EPlastDBContext.cs
> +            modelBuilder.Entity<Area>(area => area.HasData
I created an extension method for modelBuilder called SeedData to store all seeding operations there, look at the end of OnModelCreating. Also all seeding operations should be called at the end of onModelCreating in order to avoid relationship problems.

2022-06-23 06:20 UTC, hryhoriivoloshyn commented on EPlast/EPlast.DataAccess/Entities/Region/Region.cs
> +        public int? AreaId { get; set; }
I don't see any reason to make this external key nullable, why? it's not like admins wouldn't know locations of their Region or City.

2022-06-23 06:20 UTC, hryhoriivoloshyn commented on EPlast/EPlast.DataAccess/Migrations/20220622210115_AreaMigration.cs
> +                name: "SectorAnnouncementImage");
Have you used the last version of master? This migration won't apply, we don't have this table anymore.

2022-06-23 07:34 UTC, tvardero requested changes
Blocking merge. Look for telegram conversation.

2022-06-23 07:36 UTC, tvardero commented
Ukraine has constant amount of regions ("areas"). Regions should be stored as C# Enum on backend, but not as SQL table.

2022-06-26 20:39 UTC, tvardero commented
Superseded by https://github.com/ita-social-projects/EPlast/pull/2578

2022-06-26 20:39 UTC, closed without merging