Add Oblast to Region
ita-social-projects/EPlast pull request #2612
Opened 2022-07-01 07:49 UTC by tvardero

2022-07-01 07:50 UTC, Omeliukh-Nazar approved these changes

2022-07-01 08:10 UTC, vsynieok approved these changes

2022-07-02 01:49 UTC, Serhii-Buniak approved these changes

2022-07-02 02:10 UTC, Serhii-Buniak requested changes

2022-07-02 02:10 UTC, Serhii-Buniak commented on EPlast/EPlast.BLL/Services/Region/RegionService.cs
> +            );
You can use `GetAllAsync(predicate: <Predicate>)` not Where

2022-07-02 02:24 UTC, Serhii-Buniak requested changes

2022-07-02 02:24 UTC, Serhii-Buniak commented on EPlast/EPlast.DataAccess/Entities/Region/Region.cs
> +        public UkraineOblasts Oblast { get; set; }
You didn't make migration for this field

2022-07-04 09:31 UTC, tvardero commented on EPlast/EPlast.BLL/Services/Region/RegionService.cs
> +            );
Fixed

2022-07-05 15:05 UTC, Serhii-Buniak approved these changes

2022-07-05 18:03 UTC, merged