add course page
ita-social-projects/EPlast pull request #2615
Opened 2022-07-01 08:57 UTC by Goven112

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2022-07-01 09:00 UTC, hryhoriivoloshyn commented on EPlast/EPlast.DataAccess/EPlast.DataAccess.csproj
> +    <Compile Remove="Entities\MethodicDocument\MethodicDocumetsTableObject.cs" />
Right click on DataAccess Project, Unload Project, edit csproj file by removining this lines, no need in them.

2022-07-01 09:13 UTC, tvardero requested changes

2022-07-01 10:06 UTC, tvardero approved these changes

2022-07-01 10:50 UTC, DimaDiD approved these changes

2022-07-01 19:12 UTC, Serhii-Buniak requested changes

2022-07-01 19:12 UTC, Serhii-Buniak commented on EPlast/EPlast.WebApi/Controllers/CourseController.cs
> +        }
return BadResult if user don'n exist

2022-07-04 09:29 UTC, Goven112 commented on EPlast/EPlast.WebApi/Controllers/CourseController.cs
> +        }
done

2022-07-04 09:39 UTC, tvardero requested changes

2022-07-04 09:39 UTC, tvardero commented on EPlast/EPlast.WebApi/Controllers/CourseController.cs
> +        }
`GetCourseByIdAsync` returns empty IEnumerable, if not found.

2022-07-06 18:31 UTC, Goven112 commented on EPlast/EPlast.WebApi/Controllers/CourseController.cs
> +        }
done

2022-07-07 05:56 UTC, tvardero approved these changes

2022-07-07 11:07 UTC, Serhii-Buniak approved these changes

2022-07-13 10:53 UTC, merged