Login fix
ita-social-projects/EPlast pull request #2708
Opened 2022-08-03 13:25 UTC by Serhii-Buniak

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2022-08-03 15:57 UTC, hryhoriivoloshyn approved these changes

2022-08-04 12:06 UTC, vsynieok approved these changes

2022-08-04 13:38 UTC, tvardero requested changes

2022-08-04 13:38 UTC, tvardero commented on EPlast/EPlast.WebApi/Controllers/LoginController.cs
> +            return BadRequest(_resources.ResourceForErrors["ModelIsNotValid"]);
Change it to `return BadRequest(ModelState);`

And, please, invert `if` statement. To reduce amount of curly braces.

2022-08-04 13:38 UTC, tvardero commented on EPlast/EPlast.WebApi/Extensions/HttpRequestExtensions.cs
> +        public static string GetFrontEndURL(this HttpRequest request, [NotNull] string queryEnd = "")
Rename `queryEnd` to `tail` to reduce confusion.

Also make it nullable. If `tail` is null or empty, then just return `frontendUrl`

2022-08-04 13:38 UTC, tvardero commented on EPlast/EPlast.BLL/Handlers/PrecautionHandlers/GetUsersPrecautionsForTableHandler.cs
>                  || x.Precaution.Name.Contains(searchedData)
What is this and why is it here?

2022-08-04 16:38 UTC, Serhii-Buniak commented on EPlast/EPlast.BLL/Handlers/PrecautionHandlers/GetUsersPrecautionsForTableHandler.cs
>                  || x.Precaution.Name.Contains(searchedData)
It`s bug on precaution(search wasn't work correct).

2022-08-05 06:14 UTC, tvardero commented on EPlast/EPlast.WebApi/Controllers/LoginController.cs
> +            if (ModelState.IsValid == false)
`if (!ModelState.IsValid)`

2022-08-05 06:14 UTC, tvardero commented on EPlast/EPlast.WebApi/Controllers/LoginController.cs
> +                return BadRequest(_resources.ResourceForErrors["Login-NotRegistered"]);
`return NotFound();` is better suited for these situations

2022-08-05 06:17 UTC, tvardero approved these changes

2022-08-06 16:29 UTC, tvardero approved these changes

2022-08-07 09:52 UTC, merged