#2556 Fix approver information
ita-social-projects/EPlast pull request #2774
Opened 2022-08-23 17:19 UTC by MaksymLiaskovskyi

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2022-08-24 05:04 UTC, tvardero commented
Як воно стосується до 2556 та як воно вирішує проблему

2022-08-24 19:56 UTC, MaksymLiaskovskyi commented
> Як воно стосується до 2556 и як воно вирішує проблему
> 
> якщо гілка ще в роботі, то роби пр як чорнетку (проект)

Фронт має виводити правильний надпис в залежності від того чи пітверджен курінь/станиця, але ця інформація не передається

2022-08-25 05:09 UTC, hryhoriivoloshyn approved these changes

2022-08-25 08:22 UTC, tvardero commented
ці два поля заповнюються автомаппером?

2022-08-25 08:30 UTC, MaksymLiaskovskyi commented
> ці два поля заповнюються автомаппером?

так

2022-08-25 08:35 UTC, tvardero approved these changes

2022-08-27 12:25 UTC, Mykola123-NMT approved these changes

2022-08-29 06:34 UTC, tvardero approved these changes

2022-09-21 14:57 UTC, tvardero requested changes
7 коммитов, 4 строки
скваш

2022-09-29 17:46 UTC, gutovskii approved these changes

2022-09-29 18:15 UTC, merged