#2622-fix
ita-social-projects/EPlast pull request #2776
Opened 2022-08-24 10:06 UTC by MishaHMK

closes https://github.com/ita-social-projects/EPlast/issues/2622

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2022-08-24 12:37 UTC, hryhoriivoloshyn requested changes

2022-08-24 12:37 UTC, hryhoriivoloshyn commented on EPlast/EPlast.WebApi/Controllers/ActiveMembershipController.cs
> +            return Ok(degrees.OrderBy(d => d.Name));
It is better to add sorting to service level, not a controller.

2022-08-24 14:42 UTC, MishaHMK commented on EPlast/EPlast.WebApi/Controllers/ActiveMembershipController.cs
> +            return Ok(degrees.OrderBy(d => d.Name));
ok, thanks

2022-08-24 17:02 UTC, tvardero commented on EPlast/EPlast.WebApi/Controllers/ActiveMembershipController.cs
> +            var degrees = await _plastDegreeService.GetDergeesAsync();
в чому сенс

2022-08-24 17:03 UTC, tvardero commented on EPlast/EPlast.WebApi/Controllers/RegionsController.cs
> +using System.Linq;
Навіщо додано

2022-08-24 17:03 UTC, tvardero commented on EPlast/EPlast.WebApi/Controllers/ClubController.cs
> +using System.Linq;
Навіщо додано

2022-08-24 17:03 UTC, tvardero commented on EPlast/EPlast.BLL/Services/Region/RegionService.cs
> +                .GetActiveRegionsNames().OrderBy(r => r.RegionName);
Перенеси сортування до GetActiveRegionsNames

2022-08-26 06:02 UTC, hryhoriivoloshyn requested changes

2022-08-26 06:02 UTC, hryhoriivoloshyn commented on EPlast/EPlast.BLL/Services/Club/ClubService.cs
> +        private Func<IQueryable<DataAccessClub.Club>, IQueryable<DataAccessClub.Club>> GetOrder()
Same here, just write lambda expression, no need in separate functions.

2022-08-29 06:29 UTC, tvardero commented on EPlast/EPlast.BLL/Services/ActiveMembership/PlastDegreeService.cs
> +        private Func<IQueryable<PlastDegree>, IQueryable<PlastDegree>> GetOrder()
@hryhoriivoloshyn I WILL HAVE ORDER

2022-08-31 05:47 UTC, hryhoriivoloshyn approved these changes

2022-08-31 15:22 UTC, tvardero submitted a review, later dismissed
Сквашни коммиты

2022-09-01 06:58 UTC, MishaHMK commented on EPlast/EPlast.BLL/Services/Club/ClubService.cs
> +            var clubs = await _repoWrapper.Club.GetRangeAsync(c => c.IsActive, null, x => x.OrderBy(e => e.Name), null, null, null);
Я так зробив, бо з поіменованими параметрами юніт-тести сварилися, що я їм повертаю null звідси

2022-09-01 09:57 UTC, Serhii-Buniak approved these changes

2022-09-01 09:57 UTC, gutovskii approved these changes

2022-09-01 13:53 UTC, merged