Restore #2703 changes
ita-social-projects/EPlast pull request #2779
Opened 2022-08-25 05:40 UTC by hryhoriivoloshyn

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2022-08-25 08:23 UTC, tvardero approved these changes

2022-08-25 08:24 UTC, tvardero commented on EPlast/EPlast.BLL/Services/UserProfiles/UserProfileAccessService.cs
> +                ((currentUserRoles.Contains(Roles.KurinHead)) && await _userService.IsUserInSameCellAsync(currentUser, focusUser, CellType.Club));
зайві дужки

2022-08-27 12:16 UTC, Mykola123-NMT approved these changes

2022-08-28 09:30 UTC, vsynieok approved these changes

2022-08-29 06:32 UTC, tvardero requested changes
йой а чого так багато коммітів

2022-08-29 16:13 UTC, hryhoriivoloshyn commented on EPlast/EPlast.BLL/Services/UserProfiles/UserProfileAccessService.cs
> +                ((currentUserRoles.Contains(Roles.KurinHead)) && await _userService.IsUserInSameCellAsync(currentUser, focusUser, CellType.Club));
Got it

2022-08-29 17:07 UTC, hryhoriivoloshyn commented
> йой а чого так багато коммітів

Here is a normal version of this pull request, I tried fixing this branch with interactive rebase but got confusing results, so I just created branch based on master and squashed changes I needed into that branch, should be much better.
https://github.com/ita-social-projects/EPlast/pull/2785

2022-08-29 17:08 UTC, closed without merging