Events modifications for 1042
ita-social-projects/EPlast pull request #2784
Opened 2022-08-28 19:40 UTC by vsynieok

This branch contains changes for back-end part of our project, that are part of the redesign, described in #1042

The pull should close following issues:
#2417 
#1663 
#2127

2022-08-29 06:25 UTC, tvardero commented on EPlast/EPlast.BLL/DTO/Events/EventInfoDTO.cs
> +        public List<int> Gallery { get; set; }
Why not IEnumerable?

2022-08-31 15:27 UTC, tvardero approved these changes

2022-08-31 15:28 UTC, tvardero commented on EPlast/EPlast.DataAccess/EPlastDBContext.cs
> +                    .HasKey(fb => fb.ID);
лишнее, еф сам делает

2022-08-31 15:31 UTC, tvardero requested changes
Есть коммит который Add Event Feedbacks

А потом следом за ним идет Revert "Add Event Feedbacks"


Почисть

2022-08-31 15:32 UTC, tvardero commented on EPlast/EPlast.DataAccess/EPlast.DataAccess.csproj
> +    <Compile Remove="Migrations\20220810125156_AAAAAAAA.cs" />
ААААААААААА?

2022-08-31 20:20 UTC, vsynieok commented on EPlast/EPlast.DataAccess/EPlast.DataAccess.csproj
> +    <Compile Remove="Migrations\20220810125156_AAAAAAAA.cs" />
я був дуже злий на ентіті фреймворк, сорі переіменую

2022-09-02 10:00 UTC, hryhoriivoloshyn requested changes
A lot of authorization logic inside services, consider moving it in user access service for events.

2022-09-05 05:25 UTC, tvardero requested changes
Занадто багато змін та не дуже гарна історія комітів (ти так і не виправив те що я казав щодо Revert "Add Event Feedbacks").

Або чисть історію комітів, або дроби на окремі пр.

2022-09-05 12:04 UTC, hryhoriivoloshyn approved these changes

2022-09-05 13:21 UTC, closed without merging