#2579-fix
ita-social-projects/EPlast pull request #2787
Opened 2022-08-30 15:09 UTC by MishaHMK

closes https://github.com/ita-social-projects/EPlast/issues/2579
check status of current head and head deputy

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2022-08-31 05:37 UTC, hryhoriivoloshyn approved these changes

2022-08-31 15:18 UTC, tvardero commented on EPlast/EPlast.BLL/Services/Region/RegionAdministrationService.cs
> +            var head = await _repoWrapper.RegionAdministration.GetFirstOrDefaultAsync(d => d.RegionId == regionId && d.AdminType.AdminTypeName == Roles.OkrugaHead
```c#
var headDeputy = await _repoWrapper.RegionAdministration
    .GetFirstOrDefaultAsync(d => 
        d.RegionId == regionId 
        && d.AdminType.AdminTypeName == Roles.OkrugaHeadDeputy 
        && (d.EndDate > DateTime.Now || d.EndDate == null) 
        && d.Status,
        include: ...)
```

Старайся чтобы строки не улетали вправо далеко, разноси по точкам
Также не очень удобно читать когда выравнивание аргументов по скобке с огромной табуляцией слева)

2022-08-31 15:18 UTC, tvardero commented on EPlast/EPlast.BLL/Services/Region/RegionAdministrationService.cs
> +                                                                                             && (d.EndDate > DateTime.Now || d.EndDate == null) && d.Status,
тут тоже

2022-08-31 15:19 UTC, tvardero requested changes
И еще, я не увидел изменений кода

2022-08-31 15:20 UTC, tvardero approved these changes

2022-09-01 14:58 UTC, gutovskii approved these changes

2022-09-05 15:45 UTC, merged