Delete HttpRequestExtensions
ita-social-projects/EPlast pull request #2827
Opened 2022-09-11 16:58 UTC by Serhii-Buniak

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2022-09-11 21:09 UTC, tvardero requested changes

2022-09-11 21:09 UTC, tvardero commented on EPlast/EPlast.BLL/Services/HostURL/HostURLService.cs
> +            return $"{BackEndApiURL}/Auth/confirmEmail?userId={userId}&token={HttpUtility.UrlEncode(token)}";
Велосипедно. Ссылки на бекенд пиши через UrlHelper.Action. Оно само правильно генерирует урлы.

2022-09-13 09:11 UTC, Serhii-Buniak commented on EPlast/EPlast.BLL/Services/HostURL/HostURLService.cs
> +            return $"{BackEndApiURL}/Auth/confirmEmail?userId={userId}&token={HttpUtility.UrlEncode(token)}";
UrlHelper.Action не працює якщо не має хоста. А хоста у нас не бачить HangFire, як результат помилка компіляції.

2022-09-13 20:20 UTC, tvardero approved these changes

2022-09-14 16:42 UTC, Mykola123-NMT approved these changes

2022-09-15 16:57 UTC, merged