New x unit tests
ita-social-projects/EPlast pull request #2962
Opened 2022-11-21 12:49 UTC by EyR1oN

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2022-11-21 21:29 UTC, Tatiana2424 approved these changes

2022-11-22 20:59 UTC, LanchevychMaxym requested changes

2022-11-22 20:59 UTC, LanchevychMaxym commented on EPlast/EPlast.Tests/Controllers/CourseControllerTest.cs
> +        public async Task GetAllTest()
Please, follow the best bractices for naming your tests: name-scenario-expected behavior.
You can find more information here - https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices

2022-11-22 20:59 UTC, LanchevychMaxym commented on EPlast/EPlast.Tests/Controllers/CourseControllerTest.cs
> +                .ReturnsAsync(GetFakeCourses());
Please, don't duplicate the code in each test, you can use [SetUp] method to performe some actions just before each test method is called.
Or you can use helper methods to setup and teardown

2022-11-22 20:59 UTC, LanchevychMaxym commented on EPlast/EPlast.Tests/Controllers/CourseControllerTest.cs
> +                .Where(n => n.Name.Equals("Course")));
Please, don't use magic strings.

2022-11-22 20:59 UTC, LanchevychMaxym commented on EPlast/EPlast.XUnitTest/Services/Educators/EducatorsStaffTypesServiceTests.cs
> +        public async Task CreateKVTypeTest()
All the comments above refers to all tests

2022-11-22 20:59 UTC, LanchevychMaxym commented on EPlast/EPlast.Tests/Controllers/CourseControllerTest.cs
> +                .Where(n => n.Name.Equals("Course")));
Having multiple asserts is not a good practice, in this case use at least Assert.Multiple to have a report about all asserts in case your test will fail

2022-11-24 08:19 UTC, maxym-lanchevych approved these changes
LGTM!

2022-11-24 08:21 UTC, LanchevychMaxym approved these changes

2022-11-24 19:14 UTC, merged