Marian labenskyi
ita-social-projects/EPlast pull request #479
Opened 2020-10-08 22:16 UTC by MarianLabensky

2020-10-09 09:12 UTC, voroniak commented on EPlast/EPlast.BLL/Services/ActiveMembership/UserDatesService.cs
> +            return null;
return null is considered a bad practice

2020-10-09 09:20 UTC, voroniak commented on EPlast/EPlast.BLL/Services/ActiveMembership/UserDatesService.cs
> +            return null;
return null is considered a bad practice

2020-10-09 12:33 UTC, MarianLabensky commented on EPlast/EPlast.BLL/Services/ActiveMembership/UserDatesService.cs
> +            return null;
Ok, I changed it, now it throw exception instead return null

2020-10-09 14:20 UTC, voroniak commented on EPlast/EPlast.BLL/Services/ActiveMembership/UserDatesService.cs
> +            return null;
It's better to fix  5 Code Smells too.

2020-10-09 14:55 UTC, MarianLabensky commented on EPlast/EPlast.BLL/Services/ActiveMembership/UserDatesService.cs
> +            return null;
Done))

2020-10-12 15:17 UTC, voroniak requested changes

2020-10-12 15:17 UTC, voroniak commented on EPlast/EPlast.Tests/Services/ActiveMembership/UserDatesServiceTests.cs
> +        /// <returns></returns>
???

2020-10-12 15:33 UTC, MarianLabensky commented on EPlast/EPlast.Tests/Services/ActiveMembership/UserDatesServiceTests.cs
> +        /// <returns></returns>
I just forgot about it, now it`s fixed

2020-10-13 09:47 UTC, voroniak approved these changes

2020-10-13 10:36 UTC, TonyWebber approved these changes

2020-10-15 11:02 UTC, MykhailoKlapchuk approved these changes

2020-10-15 11:08 UTC, merged