Add city service nunit tests
ita-social-projects/EPlast pull request #481
Opened 2020-10-10 21:18 UTC by tetyanakutsko

2020-10-10 21:42 UTC, WanDER33 approved these changes

2020-10-10 22:13 UTC, MykhailoKlapchuk approved these changes

2020-10-11 02:08 UTC, voroniak requested changes

2020-10-11 02:08 UTC, voroniak commented on EPlast/EPlast.Tests/Services/City/CityMembersServiceTests.cs
> +    class CityMembersService
!????

2020-10-11 02:08 UTC, voroniak commented on EPlast/EPlast.Tests/Services/City/CityServiceTests.cs
> +        public async Task GetCitiesByRegionAsync_ReturnsCities()
Return or returns?  
I sing where you might have to use some rules.
You may use return or returns.
But here is one rule to use one of  them.

2020-10-11 17:36 UTC, tetyanakutsko commented on EPlast/EPlast.Tests/Services/City/CityMembersServiceTests.cs
> +    class CityMembersService
Thanks. Was aded by mistake. Deleted already

2020-10-12 11:24 UTC, voroniak commented on EPlast/EPlast.Tests/Services/City/CityServiceTests.cs
> +        public IQueryable<CityDTO> CreateFakeCityDto(int count)
it seems to me that the methods that return test data in tests should be private

2020-10-12 11:24 UTC, voroniak commented on EPlast/EPlast.Tests/Services/City/CityServiceTests.cs
> +            return region;
```suggestion
            return new Region()
            {
                ID = 1,
                RegionName = "Lviv",
                Description = "Lviv region"
            };
\
```

2020-10-12 11:25 UTC, voroniak commented on EPlast/EPlast.Tests/Services/City/CityServiceTests.cs
> +            return city;
```suggestion
           return new DataAccessCity.City
            {
                Name = "city",
                Logo = "710b8b06-6869-45db-894f-7a0b131e6c6b.jpg"
            };

```

2020-10-13 21:23 UTC, tetyanakutsko commented on EPlast/EPlast.Tests/Services/City/CityServiceTests.cs
> +            return city;
Thanks a lot!!!
It's changed.

2020-10-14 10:27 UTC, voroniak approved these changes
LGTM!

2020-10-14 10:28 UTC, merged