Added new method for getting all member statistics from all annual re…
ita-social-projects/EPlast pull request #503
Opened 2020-10-17 14:52 UTC by MykhailoKlapchuk

…ports

2020-10-17 15:26 UTC, voroniak requested changes

2020-10-17 15:26 UTC, voroniak commented on EPlast/EPlast.BLL/Services/Statistics/StatisticsService.cs
> +            return membersStatistics;
```suggestion
            return annualReports.Select(report => report.MembersStatistic);
```
I'm not sure, but you can write something like that.

Why don`t you use DTO ? As I understand, Members Statistic from Data Access

2020-10-18 10:21 UTC, voroniak approved these changes
LGTM!

2020-10-18 12:18 UTC, MarianLabensky approved these changes

2020-10-18 20:38 UTC, Yuriyhp approved these changes

2020-10-18 23:03 UTC, merged