Logick for Blank Achievement List
ita-social-projects/EPlast pull request #504
Opened 2020-10-18 15:55 UTC by Yuriyhp

2020-10-18 20:01 UTC, voroniak requested changes

2020-10-18 20:20 UTC, Yuriyhp commented on EPlast/EPlast.BLL/Services/Blank/BlankBiographyDocumentsService.cs
> +            return StatusCodes.Status204NoContent;
))

2020-10-18 22:54 UTC, MykhailoKlapchuk approved these changes

2020-10-19 10:30 UTC, voroniak approved these changes
LGTM!

2020-10-19 10:40 UTC, ViktorKalynenko approved these changes

2020-10-19 10:40 UTC, MarianLabensky approved these changes

2020-10-19 10:41 UTC, merged