Google Authorization
ita-social-projects/EPlast pull request #576
Opened 2020-10-28 01:31 UTC by LanchevychMaxym

2020-10-28 05:30 UTC, tetyanakutsko approved these changes

2020-10-28 06:22 UTC, voroniak requested changes

2020-10-28 06:22 UTC, voroniak commented on EPlast/EPlast.BLL/Models/GoogleApiTokenInfo.cs
> +        public string iss { get; set; }
```suggestion
        public string Iss { get; set; }
```

2020-10-28 06:22 UTC, voroniak commented on EPlast/EPlast.BLL/Models/GoogleApiTokenInfo.cs
> +        public string at_hash { get; set; }
```suggestion
        public string AtHash { get; set; }
```

2020-10-28 06:22 UTC, voroniak commented on EPlast/EPlast.BLL/Models/GoogleApiTokenInfo.cs
> +        public string aud { get; set; }
```suggestion
        public string Aud { get; set; }
```

2020-10-28 06:22 UTC, voroniak commented on EPlast/EPlast.BLL/Models/GoogleApiTokenInfo.cs
> +        public string sub { get; set; }
```suggestion
        public string Sub { get; set; }
```

2020-10-28 06:22 UTC, voroniak commented on EPlast/EPlast.BLL/Models/GoogleApiTokenInfo.cs
> +        public string email_verified { get; set; }
```suggestion
        public string EmailVerified { get; set; }
```

2020-10-28 06:22 UTC, voroniak commented on EPlast/EPlast.BLL/Models/GoogleApiTokenInfo.cs
> +        public string azp { get; set; }
```suggestion
        public string Azp { get; set; }
```

2020-10-28 06:22 UTC, voroniak commented on EPlast/EPlast.BLL/Models/GoogleApiTokenInfo.cs
> +        public string email { get; set; }
```suggestion
        public string Email { get; set; }
```

2020-10-28 06:22 UTC, voroniak commented on EPlast/EPlast.BLL/Models/GoogleApiTokenInfo.cs
> +        public string iat { get; set; }
```suggestion
        public string Iat { get; set; }
```

2020-10-28 06:22 UTC, voroniak commented on EPlast/EPlast.BLL/Models/GoogleApiTokenInfo.cs
> +        public string exp { get; set; }
```suggestion
        public string Exp { get; set; }
```

2020-10-28 06:22 UTC, voroniak commented on EPlast/EPlast.BLL/Models/GoogleApiTokenInfo.cs
> +        public string name { get; set; }
```suggestion
        public string Name { get; set; }
```

2020-10-28 06:22 UTC, voroniak commented on EPlast/EPlast.BLL/Models/GoogleApiTokenInfo.cs
> +        public string picture { get; set; }
```suggestion
        public string Picture { get; set; }
```

2020-10-28 06:22 UTC, voroniak commented on EPlast/EPlast.BLL/Models/GoogleApiTokenInfo.cs
> +        public string given_name { get; set; }
```suggestion
        public string GivenName { get; set; }
```

2020-10-28 06:22 UTC, voroniak commented on EPlast/EPlast.BLL/Models/GoogleApiTokenInfo.cs
> +        public string family_name { get; set; }
```suggestion
        public string FamilyName { get; set; }
```

2020-10-28 06:22 UTC, voroniak commented on EPlast/EPlast.BLL/Models/GoogleApiTokenInfo.cs
> +        public string locale { get; set; }
```suggestion
        public string Locale { get; set; }
```

2020-10-28 06:22 UTC, voroniak commented on EPlast/EPlast.BLL/Models/GoogleApiTokenInfo.cs
> +        public string alg { get; set; }
```suggestion
        public string Alg { get; set; }
```

2020-10-28 06:22 UTC, voroniak commented on EPlast/EPlast.BLL/Models/GoogleApiTokenInfo.cs
> +        public string kid { get; set; }
```suggestion
        public string Kid { get; set; }
```

2020-10-28 06:22 UTC, voroniak commented on EPlast/EPlast.BLL/Services/Auth/AuthService.cs
> +            HttpResponseMessage httpResponseMessage = httpClient.GetAsync(requestUri).Result;
```suggestion
            HttpResponseMessage httpResponseMessage = await httpClient.GetAsync(requestUri)
```
Why don't we use this?

2020-10-28 06:22 UTC, voroniak commented on EPlast/EPlast.BLL/Services/Auth/AuthService.cs
> +            var response = httpResponseMessage.Content.ReadAsStringAsync().Result;
?

2020-10-28 06:22 UTC, voroniak commented on EPlast/EPlast.WebApi/Controllers/AuthController.cs
> +using EPlast.DataAccess.Entities;
Why do we have reference to Data Access?

2020-10-28 08:05 UTC, LanchevychMaxym commented on EPlast/EPlast.WebApi/Controllers/AuthController.cs
> +using EPlast.DataAccess.Entities;
I've already fixed it, thanks.

2020-10-28 08:44 UTC, MarianLabensky approved these changes

2020-10-29 15:56 UTC, tarasvolosheniuk approved these changes

2020-10-29 16:28 UTC, MykhailoKlapchuk approved these changes

2020-10-30 12:14 UTC, voroniak approved these changes

2020-10-30 12:25 UTC, merged