Changed real-time connection from SignalR to WebSockets
ita-social-projects/EPlast pull request #578
Opened 2020-10-28 16:36 UTC by MarianLabensky

2020-11-02 10:45 UTC, atarason requested changes

2020-11-02 22:41 UTC, MarianLabensky commented on EPlast/EPlast.BLL/Services/Notifications/NotificationConnectionManager.cs
> +                userMap[userId].Remove(userMap[userId].FirstOrDefault(e => e.ConnectionId == connectionId));
Yes, it can return null, and I rewrite this.

2020-11-02 22:48 UTC, MarianLabensky commented on EPlast/EPlast.WebApi/CustomMiddlewares/WebSocketMiddleware.cs
> +
ok

2020-11-02 22:50 UTC, MarianLabensky commented on EPlast/EPlast.BLL/Services/Notifications/NotificationConnectionManager.cs
> +
Yes, I did it.

2020-11-02 23:08 UTC, MarianLabensky commented on EPlast/EPlast.WebApi/WebSocketHandlers/UserNotificationHandler.cs
> +        {
This method will never be called, because I don`t need receiving message from client-side in notifications.
But I have to realize this method, because it`s abstract in the base class: BaseWebSocketHandler.
Instead of throwing exception I add sending message to sender.

2020-11-02 23:13 UTC, MarianLabensky commented on EPlast/EPlast.BLL/Services/Notifications/NotificationConnectionManager.cs
> +        {
Added

2020-11-05 23:32 UTC, MarianLabensky commented on EPlast/EPlast.BLL/Services/Notifications/NotificationConnectionManager.cs
> +        {
Done!

2020-11-07 09:32 UTC, voroniak requested changes

2020-11-07 09:32 UTC, voroniak commented on EPlast/EPlast.WebApi/WebSocketHandlers/BaseWebSocketHandler.cs
> +        public virtual async Task OnDisconnected(string userId, string connectionId)
```suggestion
        public virtual async Task OnDisconnectedAsync(string userId, string connectionId)
```

2020-11-07 09:32 UTC, voroniak commented on EPlast/EPlast.BLL/Interfaces/Notifications/INotificationConnectionManager.cs
> +        Task<bool> RemoveSocket(string userId, string connectionId);
```suggestion
        Task<bool> RemoveSocketAsync(string userId, string connectionId);
```

2020-11-07 15:59 UTC, MarianLabensky commented on EPlast/EPlast.BLL/Interfaces/Notifications/INotificationConnectionManager.cs
> +        Task<bool> RemoveSocket(string userId, string connectionId);
Done!

2020-11-07 15:59 UTC, MarianLabensky commented on EPlast/EPlast.WebApi/WebSocketHandlers/BaseWebSocketHandler.cs
> +        public virtual async Task OnDisconnected(string userId, string connectionId)
Done!

2020-11-07 20:16 UTC, voroniak approved these changes

2020-11-09 10:12 UTC, atarason requested changes

2020-11-09 10:12 UTC, atarason commented on EPlast/EPlast.BLL/Services/City/CityDocumentsService.cs
> +            var fileName = _uniqueId.GetUniqueId() + extension;
Please use this approach to interpolate string https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated

2020-11-09 10:12 UTC, atarason commented on EPlast/EPlast.BLL/Services/City/CityService.cs
> +                    var fileName = _uniqueId.GetUniqueId() + Path.GetExtension(file.FileName);
Please use this approach to interpolate string https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated.

What value does Path.GetExtension method return ?

2020-11-09 10:12 UTC, atarason commented on EPlast/EPlast.BLL/Services/City/CityService.cs
> +                var fileName = _uniqueId.GetUniqueId() + extension;
Please use this approach to interpolate string https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated.

2020-11-09 10:12 UTC, atarason commented on EPlast/EPlast.BLL/Services/Club/ClubDocumentsService.cs
> +            var fileName = _uniqueId.GetUniqueId() + extension;
Please use this approach to interpolate string https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated.

2020-11-09 10:12 UTC, atarason commented on EPlast/EPlast.BLL/Services/Club/ClubService.cs
> +                    var fileName = _uniqueId.GetUniqueId() + Path.GetExtension(file.FileName);
Please use this approach to interpolate string https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated.

2020-11-09 10:12 UTC, atarason commented on EPlast/EPlast.BLL/Services/Decision/DecisionService.cs
> +                repoDecision.FileName = _uniqueId.GetUniqueId() + repoDecision.FileName;
Please use this approach to interpolate string https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated.

2020-11-09 10:12 UTC, atarason commented on EPlast/EPlast.BLL/Services/Events/EventGalleryManager.cs
> +                    var fileName = _uniqueId.GetUniqueId() + Path.GetExtension(file.FileName);
Please use this approach to interpolate string https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated.

2020-11-09 10:12 UTC, atarason commented on EPlast/EPlast.BLL/Services/Region/RegionService.cs
> +             var fileName = _uniqueId.GetUniqueId() + extension;
Please use this approach to interpolate string https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated.

2020-11-09 10:12 UTC, atarason commented on EPlast/EPlast.BLL/Services/UserProfiles/UserService.cs
> +                var fileName = _uniqueId.GetUniqueId().ToString() + "." + ext;
Please use this approach to interpolate string https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated.

2020-11-09 10:12 UTC, atarason commented on EPlast/EPlast.BLL/Services/Notifications/NotificationConnectionManager.cs
> +            return userMap.FirstOrDefault(p => p.Value.FirstOrDefault(conn => conn.WebSocket == socket) != null).Key;
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/member-access-operators#null-conditional-operators--and- 
make sure that userMap.FirstOrDefault can't be nulluserMap.FirstOrDefault

2020-11-09 16:32 UTC, MarianLabensky commented on EPlast/EPlast.BLL/Services/City/CityDocumentsService.cs
> +            var fileName = _uniqueId.GetUniqueId() + extension;
Done

2020-11-09 16:37 UTC, MarianLabensky commented on EPlast/EPlast.BLL/Services/City/CityService.cs
> +                    var fileName = _uniqueId.GetUniqueId() + Path.GetExtension(file.FileName);
It returns string or null, or System.String.Empty.
Done.

2020-11-09 16:38 UTC, MarianLabensky commented on EPlast/EPlast.BLL/Services/Club/ClubDocumentsService.cs
> +            var fileName = _uniqueId.GetUniqueId() + extension;
Done

2020-11-09 16:38 UTC, MarianLabensky commented on EPlast/EPlast.BLL/Services/City/CityService.cs
> +                var fileName = _uniqueId.GetUniqueId() + extension;
Done

2020-11-09 16:38 UTC, MarianLabensky commented on EPlast/EPlast.BLL/Services/Club/ClubService.cs
> +                    var fileName = _uniqueId.GetUniqueId() + Path.GetExtension(file.FileName);
Done

2020-11-09 16:38 UTC, MarianLabensky commented on EPlast/EPlast.BLL/Services/Decision/DecisionService.cs
> +                repoDecision.FileName = _uniqueId.GetUniqueId() + repoDecision.FileName;
Done

2020-11-09 16:39 UTC, MarianLabensky commented on EPlast/EPlast.BLL/Services/Events/EventGalleryManager.cs
> +                    var fileName = _uniqueId.GetUniqueId() + Path.GetExtension(file.FileName);
Done

2020-11-09 16:40 UTC, MarianLabensky commented on EPlast/EPlast.BLL/Services/Region/RegionService.cs
> +             var fileName = _uniqueId.GetUniqueId() + extension;
Done

2020-11-09 16:40 UTC, MarianLabensky commented on EPlast/EPlast.BLL/Services/UserProfiles/UserService.cs
> +                var fileName = _uniqueId.GetUniqueId().ToString() + "." + ext;
Done

2020-11-09 16:46 UTC, MarianLabensky commented on EPlast/EPlast.BLL/Services/Notifications/NotificationConnectionManager.cs
> +            return userMap.FirstOrDefault(p => p.Value.FirstOrDefault(conn => conn.WebSocket == socket) != null).Key;
I added checking on default value.

2020-11-10 08:35 UTC, atarason approved these changes

2020-11-10 12:24 UTC, bodnarira approved these changes

2020-11-10 12:24 UTC, tetyanakutsko approved these changes

2020-11-10 13:23 UTC, LanchevychMaxym approved these changes

2020-11-10 14:15 UTC, merged