Changing roles by admin
ita-social-projects/EPlast pull request #600
Opened 2020-10-30 17:36 UTC by bodnarira

2020-10-30 18:23 UTC, LanchevychMaxym approved these changes

2020-10-30 18:29 UTC, voroniak commented on EPlast/EPlast.BLL/Interfaces/Club/IClubMembersService.cs
> +        /// <param name="member">The member of the club</param>
But why is the class called ClubMembers?)))

2020-10-30 18:51 UTC, bodnarira commented on EPlast/EPlast.BLL/Interfaces/Club/IClubMembersService.cs
> +        /// <param name="member">The member of the club</param>
I don't know, it's not my class((((

2020-10-31 22:11 UTC, MarianLabensky approved these changes

2020-10-31 22:29 UTC, MykhailoKlapchuk approved these changes

2020-11-01 16:20 UTC, bodnarira commented on EPlast/EPlast.BLL/Services/Admin/AdminService.cs
> +                case "Колишній член пласту":
👌

2020-11-01 22:38 UTC, voroniak requested changes

2020-11-02 08:04 UTC, voroniak approved these changes

2020-11-02 08:09 UTC, merged