Add Facebook authorization
ita-social-projects/EPlast pull request #645
Opened 2020-11-05 20:05 UTC by LanchevychMaxym

2020-11-05 20:06 UTC, tetyanakutsko approved these changes

2020-11-05 20:07 UTC, voroniak requested changes

2020-11-05 20:07 UTC, voroniak commented on EPlast/EPlast.BLL/Interfaces/Auth/IAuthService.cs
> +        Task<UserDTO> FacebookLogin(FacebookUserInfo facebookUser);
```suggestion
        Task<UserDTO> FacebookLoginAsync(FacebookUserInfo facebookUser);
```

2020-11-05 20:11 UTC, LanchevychMaxym commented on EPlast/EPlast.BLL/Interfaces/Auth/IAuthService.cs
> +        Task<UserDTO> FacebookLogin(FacebookUserInfo facebookUser);
Thanks, I've fix it

2020-11-05 20:16 UTC, Yuriyhp approved these changes

2020-11-05 21:04 UTC, MykhailoKlapchuk approved these changes

2020-11-06 12:14 UTC, voroniak requested changes

2020-11-06 12:14 UTC, voroniak commented on EPlast/EPlast.WebApi/Controllers/AuthController.cs
> +        public IActionResult FacebookAppId()
```suggestion
        public IActionResult GetFacebookAppId()
```

2020-11-06 12:14 UTC, voroniak commented on EPlast/EPlast.BLL/Models/FacebookUserInfo.cs
> +
```suggestion
```

2020-11-06 12:14 UTC, voroniak commented on EPlast/EPlast.BLL/Interfaces/Auth/IAuthService.cs
> +
```suggestion
```

2020-11-06 12:14 UTC, voroniak commented on EPlast/EPlast.WebApi/Controllers/AuthController.cs
> +
```suggestion
                var user = await _authService.FacebookLoginAsync(userInfo);
                if (user == null)
                {
                    return BadRequest();
                }
                var generatedToken = await _jwtService.GenerateJWTTokenAsync(user);

                return Ok(new { token = generatedToken });

```
Don't we have default error handling implemented?

2020-11-06 14:45 UTC, voroniak approved these changes
LGTM!

2020-11-06 14:59 UTC, merged