Region annual reports
ita-social-projects/EPlast pull request #650
Opened 2020-11-07 17:57 UTC by tetyanakutsko

2020-11-07 18:48 UTC, voroniak requested changes

2020-11-07 18:48 UTC, voroniak commented on EPlast/EPlast.BLL/DTO/Region/RegionAnnualReportDTO.cs
> +        public User User { get; set; }
Why entity from DA exist in DTO ?

2020-11-07 18:48 UTC, voroniak commented on EPlast/EPlast.BLL/DTO/Region/RegionAnnualReportDTO.cs
> +
Remove unnecessary spaces

2020-11-07 18:48 UTC, voroniak commented on EPlast/EPlast.BLL/DTO/Region/RegionAnnualReportDTO.cs
> +
Remove unnecessary spaces

2020-11-07 18:48 UTC, voroniak commented on EPlast/EPlast.BLL/DTO/Region/RegionAnnualReportDTO.cs
> +
Remove unnecessary spaces

2020-11-07 18:48 UTC, voroniak commented on EPlast/EPlast.BLL/Interfaces/Region/IRegionAccessGetter.cs
> +        Task<IEnumerable<DatabaseEntities.Region>> GetRegion(string userId);
Why does the service returns entity from DA?

2020-11-07 18:48 UTC, voroniak commented on EPlast/EPlast.BLL/Interfaces/Region/IRegionAccessGetter.cs
> +        Task<IEnumerable<DatabaseEntities.Region>> GetRegion(string userId);
```suggestion
        Task<IEnumerable<DatabaseEntities.Region>> GetRegionAsync(string userId);
```

2020-11-07 18:48 UTC, voroniak commented on EPlast/EPlast.BLL/Interfaces/Region/IRegionAnnualReportService.cs
> +        Task<RegionAnnualReportDTO> GetReportById(int id,int year);
```suggestion
        Task<RegionAnnualReportDTO> GetReportByIdAsync(int id,int year);
```

2020-11-07 18:48 UTC, voroniak commented on EPlast/EPlast.BLL/Interfaces/Region/IRegionAnnualReportService.cs
> +        Task<IEnumerable<RegionAnnualReportDTO>> GetAllRegionsReports();
```suggestion
        Task<IEnumerable<RegionAnnualReportDTO>> GetAllRegionsReportsAsync();
```

2020-11-07 18:48 UTC, voroniak commented on EPlast/EPlast.BLL/Services/Region/RegionAnnualReportService.cs
> +                throw new InvalidOperationException();
It's better to add message to your exception

2020-11-07 18:48 UTC, voroniak commented on EPlast/EPlast.BLL/Services/Region/RegionAnnualReportService.cs
> +                throw new UnauthorizedAccessException();
It's better to add message to your exception

2020-11-07 18:48 UTC, voroniak commented on EPlast/EPlast.DataAccess/Entities/Region/RegionAnnualReport.cs
> +        public string RegionName { get; set; }
As I understand Region contains Name, or not ?

2020-11-07 18:48 UTC, voroniak commented on EPlast/EPlast.WebApi/Controllers/RegionsController.cs
> +            return Ok();
It's better to return other status code, I guess) like NoContent

2020-11-07 19:10 UTC, tetyanakutsko commented on EPlast/EPlast.BLL/DTO/Region/RegionAnnualReportDTO.cs
> +
Thanks. Removed.

2020-11-07 19:10 UTC, tetyanakutsko commented on EPlast/EPlast.BLL/DTO/Region/RegionAnnualReportDTO.cs
> +
Thanks. Removed.

2020-11-07 19:10 UTC, tetyanakutsko commented on EPlast/EPlast.BLL/DTO/Region/RegionAnnualReportDTO.cs
> +
Thanks. Removed.

2020-11-07 19:10 UTC, tetyanakutsko commented on EPlast/EPlast.BLL/DTO/Region/RegionAnnualReportDTO.cs
> +        public User User { get; set; }
Thanks. Removed.

2020-11-07 19:12 UTC, tetyanakutsko commented on EPlast/EPlast.BLL/Interfaces/Region/IRegionAccessGetter.cs
> +        Task<IEnumerable<DatabaseEntities.Region>> GetRegion(string userId);
Thanks. Changed.

2020-11-07 19:18 UTC, tetyanakutsko commented on EPlast/EPlast.BLL/Interfaces/Region/IRegionAnnualReportService.cs
> +        Task<RegionAnnualReportDTO> GetReportById(int id,int year);
Thanks. Changed.

2020-11-07 19:19 UTC, tetyanakutsko commented on EPlast/EPlast.BLL/Interfaces/Region/IRegionAnnualReportService.cs
> +        Task<IEnumerable<RegionAnnualReportDTO>> GetAllRegionsReports();
Thanks. Changed.

2020-11-07 19:20 UTC, tetyanakutsko commented on EPlast/EPlast.DataAccess/Entities/Region/RegionAnnualReport.cs
> +        public string RegionName { get; set; }
Thanks. Changed.

2020-11-07 19:23 UTC, tetyanakutsko commented on EPlast/EPlast.WebApi/Controllers/RegionsController.cs
> +            return Ok();
done. Thanks

2020-11-07 21:23 UTC, LanchevychMaxym requested changes

2020-11-07 21:23 UTC, LanchevychMaxym commented on EPlast/EPlast.BLL/Services/Region/RegionAnnualReportService.cs
> +                           x += y.AnnualReports.Aggregate(0, (z, p) => z += p.MembersStatistic.NumberOfSeigneurMembers)),
Here you take statistic of all years, but I think you have to take only statistic of year that you pass in your method.

2020-11-07 21:23 UTC, LanchevychMaxym commented on EPlast/EPlast.BLL/Services/Region/RegionAnnualReportService.cs
> +                    x += y.AnnualReports.Aggregate(0, (z, p) => z += p.NumberOfTeachers)),
Here is the same issues I've described above

2020-11-08 12:48 UTC, tetyanakutsko commented on EPlast/EPlast.BLL/Services/Region/RegionAnnualReportService.cs
> +                throw new InvalidOperationException();
Done. Thanks

2020-11-08 18:30 UTC, tetyanakutsko commented on EPlast/EPlast.BLL/Services/Region/RegionAnnualReportService.cs
> +                           x += y.AnnualReports.Aggregate(0, (z, p) => z += p.MembersStatistic.NumberOfSeigneurMembers)),
Changed! Thanks

2020-11-10 17:56 UTC, MykhailoKlapchuk approved these changes

2020-11-10 17:59 UTC, MykhailoKlapchuk approved these changes

2020-11-10 18:55 UTC, LanchevychMaxym requested changes

2020-11-10 18:55 UTC, LanchevychMaxym commented on EPlast/EPlast.BLL/Services/Region/RegionAnnualReportService.cs
> +            var AnnualReports = new List<AnnualReport>();
Name AnnualReports does not match rule 'Local variables'. Suggested name is annualReports.

2020-11-10 18:55 UTC, LanchevychMaxym commented on EPlast/EPlast.BLL/Services/Region/RegionAnnualReportService.cs
> +            var MembersStatistics = new List<MembersStatistic>();
Name MembersStatisticsdoes not match rule 'Local variables'. Suggested name is membersStatistics.

2020-11-10 18:56 UTC, bodnarira approved these changes

2020-11-10 19:13 UTC, tetyanakutsko commented on EPlast/EPlast.BLL/Services/Region/RegionAnnualReportService.cs
> +            var MembersStatistics = new List<MembersStatistic>();
Changed

2020-11-10 19:13 UTC, tetyanakutsko commented on EPlast/EPlast.BLL/Services/Region/RegionAnnualReportService.cs
> +            var AnnualReports = new List<AnnualReport>();
Thanks! Changed

2020-11-10 19:22 UTC, voroniak approved these changes

2020-11-10 19:22 UTC, voroniak commented on EPlast/EPlast.BLL/Services/Region/RegionAnnualReportService.cs
> +                if (reports.Count() > 0)
```suggestion
                if (reports.Count > 0)
```

2020-11-10 19:57 UTC, LanchevychMaxym approved these changes

2020-11-10 19:58 UTC, merged