Statistics refactoring
ita-social-projects/EPlast pull request #659
Opened 2020-11-09 17:35 UTC by MykhailoKlapchuk

2020-11-09 17:54 UTC, bodnarira approved these changes

2020-11-09 18:23 UTC, MarianLabensky approved these changes

2020-11-09 21:45 UTC, voroniak requested changes

2020-11-09 21:45 UTC, voroniak commented on EPlast/EPlast.WebApi/Controllers/StatisticsController.cs
> +        public async Task<IActionResult> GetForCitiesForYears( [FromQuery] StatisticsParameters statisticsParameters)
Could you explain name of this method ?

2020-11-09 21:45 UTC, voroniak commented on EPlast/EPlast.WebApi/Controllers/StatisticsController.cs
> +            }
Why did you write this try/catch ?

2020-11-09 21:45 UTC, voroniak commented on EPlast/EPlast.WebApi/Controllers/StatisticsController.cs
> +            }
Why did you write this try/catch ?

2020-11-09 21:45 UTC, voroniak commented on EPlast/EPlast.BLL/DTO/Statistics/StatisticsItemIndicator.cs
> +
remove extra spaces

2020-11-09 22:56 UTC, MykhailoKlapchuk commented on EPlast/EPlast.WebApi/Controllers/StatisticsController.cs
> +        public async Task<IActionResult> GetForCitiesForYears( [FromQuery] StatisticsParameters statisticsParameters)
I agree with you, it is weird name. Changed.

2020-11-09 22:59 UTC, MykhailoKlapchuk commented on EPlast/EPlast.BLL/DTO/Statistics/StatisticsItemIndicator.cs
> +
I I disagree with you, it is more convenient to read with spaces.

2020-11-09 23:06 UTC, MykhailoKlapchuk commented on EPlast/EPlast.WebApi/Controllers/StatisticsController.cs
> +            }
Changed

2020-11-09 23:06 UTC, MykhailoKlapchuk commented on EPlast/EPlast.WebApi/Controllers/StatisticsController.cs
> +            }
Changed

2020-11-10 10:45 UTC, LanchevychMaxym approved these changes

2020-11-10 18:48 UTC, voroniak commented on EPlast/EPlast.BLL/DTO/Statistics/StatisticsItemIndicator.cs
> +
Yes, but we do it either everywhere in the code or nowhere. Consistency must be maintained.

2020-11-10 18:53 UTC, voroniak approved these changes

2020-11-10 19:24 UTC, merged