Regions tests
ita-social-projects/EPlast pull request #743
Opened 2020-12-17 13:09 UTC by AlexKaschuk

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2020-12-17 13:21 UTC, tetyanakutsko commented on EPlast/EPlast.Tests/Controllers/RegionsControllerTests.cs
> +
Remove unnecessary spaces

2020-12-17 13:22 UTC, tetyanakutsko reviewed
Great job !

2020-12-17 13:34 UTC, LanchevychMaxym requested changes

2020-12-17 13:34 UTC, LanchevychMaxym commented on EPlast/EPlast.Tests/Controllers/RegionsControllerTests.cs
> +
Redundant comment and line

2020-12-17 13:34 UTC, LanchevychMaxym commented on EPlast/EPlast.Tests/Controllers/RegionsControllerTests.cs
> +
the same issue

2020-12-17 13:34 UTC, LanchevychMaxym commented on EPlast/EPlast.Tests/Controllers/RegionsControllerTests.cs
> +
?

2020-12-17 13:34 UTC, LanchevychMaxym commented on EPlast/EPlast.Tests/Controllers/RegionsControllerTests.cs
> +
?

2020-12-17 13:40 UTC, AlexKaschuk commented on EPlast/EPlast.Tests/Controllers/RegionsControllerTests.cs
> +
done

2020-12-17 13:40 UTC, AlexKaschuk commented on EPlast/EPlast.Tests/Controllers/RegionsControllerTests.cs
> +
done

2020-12-17 13:40 UTC, AlexKaschuk commented on EPlast/EPlast.Tests/Controllers/RegionsControllerTests.cs
> +
done

2020-12-17 13:40 UTC, AlexKaschuk commented on EPlast/EPlast.Tests/Controllers/RegionsControllerTests.cs
> +
done

2020-12-17 13:41 UTC, AlexKaschuk commented on EPlast/EPlast.Tests/Controllers/RegionsControllerTests.cs
> +
done

2020-12-17 13:42 UTC, bodnarira approved these changes

2020-12-17 13:59 UTC, voroniak requested changes

2020-12-17 13:59 UTC, voroniak commented on EPlast/EPlast.Tests/Controllers/RegionsControllerTests.cs
> +        private  Mock<IRegionAnnualReportService> _RegionAnnualReportService;
```suggestion
        private  Mock<IRegionAnnualReportService> _regionAnnualReportService;
```

2020-12-17 13:59 UTC, voroniak commented on EPlast/EPlast.Tests/Services/Regions/RegionServiceTest.cs
> +        private readonly IEnumerable<RegionAdministration> Admins = new List<RegionAdministration>
```suggestion
        private readonly IEnumerable<RegionAdministration> _admins = new List<RegionAdministration>
```

2020-12-17 14:00 UTC, ostappppppp commented on EPlast/EPlast.Tests/Controllers/RegionsControllerTests.cs
> +        private  Mock<IRegionAnnualReportService> _RegionAnnualReportService;
as all of yours properties named form lowercase, rename _RegionAnnualReportService

2020-12-17 14:01 UTC, ostappppppp commented on EPlast/EPlast.Tests/Controllers/RegionsControllerTests.cs
> +        private RegionsController _RegionController;
also here

2020-12-17 14:13 UTC, AlexKaschuk commented on EPlast/EPlast.Tests/Controllers/RegionsControllerTests.cs
> +        private  Mock<IRegionAnnualReportService> _RegionAnnualReportService;
done

2020-12-17 14:13 UTC, AlexKaschuk commented on EPlast/EPlast.Tests/Services/Regions/RegionServiceTest.cs
> +        private readonly IEnumerable<RegionAdministration> Admins = new List<RegionAdministration>
done

2020-12-17 14:13 UTC, AlexKaschuk commented on EPlast/EPlast.Tests/Controllers/RegionsControllerTests.cs
> +        private  Mock<IRegionAnnualReportService> _RegionAnnualReportService;
done

2020-12-17 14:14 UTC, AlexKaschuk commented on EPlast/EPlast.Tests/Controllers/RegionsControllerTests.cs
> +        private RegionsController _RegionController;
done

2020-12-17 18:13 UTC, LanchevychMaxym approved these changes

2020-12-18 13:28 UTC, voroniak approved these changes

2020-12-18 13:40 UTC, merged