Fix hotspots
ita-social-projects/EPlast pull request #764
Opened 2020-12-22 18:05 UTC by LanchevychMaxym

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2020-12-22 18:07 UTC, tetyanakutsko approved these changes
Great job 👏 👍 👌

2020-12-22 18:09 UTC, bodnarira commented on EPlast/EPlast.BLL/Interfaces/Events/IActionManager.cs
>          /// <param name="user">ClaimsPrincipal of logged in user</param>
Change description

2020-12-22 18:10 UTC, voroniak requested changes

2020-12-22 18:10 UTC, voroniak commented on EPlast/EPlast.BLL/Interfaces/Events/IActionManager.cs
> +        Task<List<GeneralEventDTO>> GetEventsAsync(int categoryId, int eventTypeId, User user);
It's better to use IEnumerable

2020-12-22 18:10 UTC, voroniak commented on EPlast/EPlast.BLL/Interfaces/Events/IActionManager.cs
> +        Task<List<GeneralEventDTO>> GetEventsByStatusAsync(int categoryId, int typeId, int status, User user);
)

2020-12-22 18:11 UTC, bodnarira commented on EPlast/EPlast.BLL/Interfaces/AnnualReport/IAnnualReportService.cs
>          /// <param name="claimsPrincipal">Authorized user</param>
Description for param

2020-12-22 18:13 UTC, bodnarira commented on EPlast/EPlast.BLL/Interfaces/Auth/IAuthService.cs
>          /// <param name="claimsPrincipal"></param>
Description

2020-12-22 18:14 UTC, bodnarira commented on EPlast/EPlast.BLL/Interfaces/Auth/IAuthService.cs
>          /// <param name="claimsPrincipal"></param>
The same

2020-12-22 18:30 UTC, bodnarira commented on EPlast/EPlast.BLL/Interfaces/Club/IClubAnnualReportService.cs
>          /// <param name="claimsPrincipal">Authorized user</param>
?

2020-12-22 18:34 UTC, bodnarira commented on EPlast/EPlast.BLL/Interfaces/Events/IActionManager.cs
>          /// <param name="user">ClaimsPrincipal of logged in user</param>
?

2020-12-22 18:43 UTC, bodnarira approved these changes

2020-12-22 18:46 UTC, MykhailoKlapchuk approved these changes

2020-12-23 19:02 UTC, LanchevychMaxym commented on EPlast/EPlast.BLL/Interfaces/Events/IActionManager.cs
>          /// <param name="user">ClaimsPrincipal of logged in user</param>
fixed

2020-12-23 19:02 UTC, LanchevychMaxym commented on EPlast/EPlast.BLL/Interfaces/Events/IActionManager.cs
> +        Task<List<GeneralEventDTO>> GetEventsAsync(int categoryId, int eventTypeId, User user);
fixed

2020-12-23 19:02 UTC, LanchevychMaxym commented on EPlast/EPlast.BLL/Interfaces/Events/IActionManager.cs
> +        Task<List<GeneralEventDTO>> GetEventsByStatusAsync(int categoryId, int typeId, int status, User user);
fixed

2020-12-23 19:09 UTC, LanchevychMaxym commented on EPlast/EPlast.BLL/Interfaces/AnnualReport/IAnnualReportService.cs
>          /// <param name="claimsPrincipal">Authorized user</param>
fixed

2020-12-23 19:09 UTC, LanchevychMaxym commented on EPlast/EPlast.BLL/Interfaces/Auth/IAuthService.cs
>          /// <param name="claimsPrincipal"></param>
fixed

2020-12-23 19:09 UTC, LanchevychMaxym commented on EPlast/EPlast.BLL/Interfaces/Auth/IAuthService.cs
>          /// <param name="claimsPrincipal"></param>
fixed

2020-12-23 19:09 UTC, LanchevychMaxym commented on EPlast/EPlast.BLL/Interfaces/Club/IClubAnnualReportService.cs
>          /// <param name="claimsPrincipal">Authorized user</param>
fixed

2020-12-23 19:09 UTC, LanchevychMaxym commented on EPlast/EPlast.BLL/Interfaces/Events/IActionManager.cs
>          /// <param name="user">ClaimsPrincipal of logged in user</param>
fixed

2020-12-23 19:30 UTC, voroniak approved these changes
LGTM!

2020-12-23 20:47 UTC, merged