Added and edited tests for Decisions and blanks
ita-social-projects/EPlast pull request #775
Opened 2020-12-27 10:38 UTC by sooooolo

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2020-12-27 10:49 UTC, LanchevychMaxym requested changes

2020-12-27 10:49 UTC, LanchevychMaxym commented on EPlast/EPlast.Tests/Services/Decision/DecisionsServiceTest.cs
> +        //private static Mock<IMapper> _mapper;
Unnecessary comment

2020-12-27 10:49 UTC, LanchevychMaxym commented on EPlast/EPlast.Tests/Services/Decision/DecisionsServiceTest.cs
> +          mapper.Setup(m => m.Map<DecisionDTO>(It.IsAny<DecisionDTO>())).Returns(new DecisionDTO());
The same issue

2020-12-27 10:49 UTC, LanchevychMaxym commented on EPlast/EPlast.Tests/Services/Decision/DecisionsServiceTest.cs
> +        }*/
??

2020-12-27 11:05 UTC, MykhailoKlapchuk requested changes

2020-12-27 11:05 UTC, MykhailoKlapchuk commented on EPlast/EPlast.Tests/Services/Decision/DecisionsServiceTest.cs
> +        }
If you write code during the template and use //Arrange //Act //Assert then use them in all tests.

2020-12-27 11:05 UTC, MykhailoKlapchuk commented on EPlast/EPlast.Tests/Services/Decision/DecisionsServiceTest.cs
> +        }*/
Delete comments

2020-12-27 11:05 UTC, MykhailoKlapchuk commented on EPlast/EPlast.Tests/Services/Decision/DecisionsServiceTest.cs
> +        }
If you write during the template and use //Arrange //Act //Assert then use them in all tests.

2020-12-27 11:05 UTC, MykhailoKlapchuk commented on EPlast/EPlast.Tests/Services/Decision/DecisionsServiceTest.cs
> +        }
If you write during the template and use //Arrange //Act //Assert then use them in all tests.

2020-12-27 11:05 UTC, MykhailoKlapchuk commented on EPlast/EPlast.Tests/Services/Decision/DecisionsServiceTest.cs
> +
delete space

2020-12-27 11:05 UTC, MykhailoKlapchuk commented on EPlast/EPlast.Tests/Services/Decision/DecisionsServiceTest.cs
> +
?

2020-12-27 11:05 UTC, MykhailoKlapchuk commented on EPlast/EPlast.Tests/Services/Decision/DecisionsServiceTest.cs
> +
?

2020-12-27 11:11 UTC, voroniak requested changes

2020-12-27 11:11 UTC, voroniak commented on EPlast/EPlast.DataAccess/Entities/Region/Region.cs
> +
Unnecessary space

2020-12-27 11:11 UTC, voroniak commented on EPlast/EPlast.Tests/Controllers/BlanksControllerTests.cs
> +            Assert.IsInstanceOf<OkObjectResult>(result);
```suggestion
            _pdfService
                .Setup(p => p.BlankCreatePDFAsync(It.IsAny<string>()));

            var result = await _blanksController.GetGenerationFile(It.IsAny<string>());

            _pdfService.Verify();
            Assert.IsNotNull(result);
            Assert.IsInstanceOf<OkObjectResult>(result);
```

2020-12-27 11:11 UTC, voroniak commented on EPlast/EPlast.Tests/Services/Blank/BlankAchievementsServiceTest.cs
> +        private AchievementDocumentsDTO AchievementDocumentsDTO => new AchievementDocumentsDTO
```suggestion
        private AchievementDocumentsDTO _achievementDocumentsDTO => new AchievementDocumentsDTO
```

2020-12-27 11:11 UTC, voroniak commented on EPlast/EPlast.Tests/Services/Blank/BlankAchievementsServiceTest.cs
> +            var result = await _achievementDocumentService.GetDocumentsByUserId(new string("1"));
Magic number

2020-12-27 11:11 UTC, voroniak commented on EPlast/EPlast.Tests/Services/Decision/DecisionsServiceTest.cs
> +        public async Task GetDecisionTest(int decisionId)
Could you change naming convention?

2020-12-27 11:11 UTC, voroniak commented on EPlast/EPlast.Tests/Services/Decision/DecisionsServiceTest.cs
> +    class DecisionsServiceTest
As I remember, unit tests for decision was already written, why do we have to write the same tests ? If it's only for new methods it could be closed.

2020-12-27 13:39 UTC, LanchevychMaxym approved these changes

2020-12-27 14:49 UTC, vovikboyko approved these changes

2020-12-27 15:01 UTC, AlexKaschuk approved these changes

2020-12-27 19:11 UTC, voroniak commented on EPlast/EPlast.Tests/Services/Blank/BlankAchievementsServiceTest.cs
> +        private AchievementDocumentsDTO AchievementDocumentsDTO => new AchievementDocumentsDTO
?

2020-12-28 14:19 UTC, MykhailoKlapchuk approved these changes

2020-12-28 18:14 UTC, vovikboyko approved these changes

2020-12-28 19:20 UTC, MykhailoKlapchuk approved these changes

2020-12-28 20:57 UTC, voroniak approved these changes
LGTM!

2020-12-28 21:02 UTC, merged