Add unit-tests for GetProfile methods in City and Club services.
ita-social-projects/EPlast pull request #784
Opened 2020-12-28 14:53 UTC by Lunaflumen

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2020-12-28 19:22 UTC, MykhailoKlapchuk requested changes

2020-12-28 19:22 UTC, MykhailoKlapchuk commented on EPlast/EPlast.Tests/Services/Club/ClubServiceTests.cs
> +            //// Arrange
Why 4 slashes?

2020-12-28 19:23 UTC, MykhailoKlapchuk commented on EPlast/EPlast.Tests/Services/Club/ClubServiceTests.cs
> +            //// Arrange
Not just in this test, but in many of them.

2020-12-28 20:35 UTC, tetyanakutsko approved these changes

2020-12-28 22:15 UTC, Lunaflumen commented on EPlast/EPlast.Tests/Services/Club/ClubServiceTests.cs
> +            //// Arrange
Sorry, forgot about this copy-paste from City to Club Service Tests

2020-12-28 23:16 UTC, LanchevychMaxym approved these changes

2020-12-29 12:09 UTC, MykhailoKlapchuk approved these changes

2020-12-29 12:09 UTC, merged