AddingPrecautionPageBack
ita-social-projects/EPlast pull request #802
Opened 2021-01-16 18:34 UTC by AlexKaschuk

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-01-16 18:36 UTC, Lunaflumen approved these changes

2021-01-16 18:41 UTC, voroniak requested changes

2021-01-16 18:41 UTC, voroniak commented on EPlast/EPlast.WebApi/Controllers/PrecautionController.cs
> +            return Ok(Precautions);
```suggestion
            return Ok(await _precautionService.GetAllPrecautionAsync());
```

2021-01-16 18:53 UTC, voroniak approved these changes

2021-01-16 18:53 UTC, AlexKaschuk commented on EPlast/EPlast.WebApi/Controllers/PrecautionController.cs
> +            return Ok(Precautions);
Done

2021-01-17 11:14 UTC, sooooolo approved these changes

2021-01-17 11:23 UTC, merged