New register and email sending
ita-social-projects/EPlast pull request #809
Opened 2021-01-20 11:03 UTC by vovikboyko

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-01-20 11:17 UTC, AlexKaschuk approved these changes

2021-01-20 11:25 UTC, voroniak requested changes

2021-01-20 11:25 UTC, voroniak commented on EPlast/EPlast.BLL/Services/Auth/AuthService.cs
> +        public async Task SendEmailReminder(string citiesUrl, UserDTO userDTO)
```suggestion
        public async Task SendEmailReminderAsync(string citiesUrl, UserDTO userDTO)
```

2021-01-20 11:25 UTC, voroniak commented on EPlast/EPlast.BLL/Services/Auth/AuthService.cs
> +        public async Task SendEmailReseting(string confirmationLink, ForgotPasswordDto forgotPasswordDto)
```suggestion
        public async Task SendEmailResetingAsync(string confirmationLink, ForgotPasswordDto forgotPasswordDto)
```

2021-01-20 11:32 UTC, tetyanakutsko commented
2code smells.. need to be fixed

2021-01-20 11:55 UTC, MykhailoKlapchuk approved these changes

2021-01-21 10:55 UTC, ostappppppp commented on EPlast/EPlast.BLL/DTO/UserProfiles/ShortUserInformationDTO.cs
> +        public bool EmailConfirmed { get; set; }
Maybe, should rename this property to "IsEmailConfirmed"?

2021-01-25 13:03 UTC, sooooolo approved these changes

2021-01-25 14:04 UTC, closed without merging