AddRegionsBoardPage
ita-social-projects/EPlast pull request #851
Opened 2021-02-05 15:41 UTC by AlexKaschuk

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-02-05 15:49 UTC, Lunaflumen approved these changes

2021-02-05 15:55 UTC, vovikboyko requested changes

2021-02-05 15:55 UTC, vovikboyko commented on EPlast/EPlast.BLL/Interfaces/GoverningBodies/IGoverningBodiesService.cs
> +
empty row

2021-02-05 15:55 UTC, vovikboyko commented on EPlast/EPlast.BLL/Services/Region/RegionService.cs
empty row

2021-02-05 15:55 UTC, vovikboyko commented on EPlast/EPlast.DataAccess/Entities/Region/Region.cs
>  }
should add emty row

2021-02-05 15:55 UTC, vovikboyko commented on EPlast/EPlast.WebApi/Controllers/GoverningBodiesController.cs
> +
a lot of empty rows

2021-02-05 15:55 UTC, vovikboyko commented on EPlast/EPlast.WebApi/Controllers/RegionsController.cs
> +
empty row

2021-02-05 15:55 UTC, vovikboyko commented on EPlast/EPlast.WebApi/Controllers/RegionsController.cs
> +            //IEnumerable<RegionDTO> regions = await _cache.GetRecordAsync<IEnumerable<RegionDTO>>(recordKey);
vommented code

2021-02-05 15:55 UTC, vovikboyko commented on EPlast/EPlast.WebApi/Controllers/RegionsController.cs
> +        public async Task<IActionResult> GetRegionsBoardAsync()
region or regionS? why plural?

2021-02-05 15:55 UTC, vovikboyko commented on EPlast/EPlast.WebApi/appsettings.json
> +    "EPlastDBConnection": "Server=tcp:eplast.database.windows.net,1433;Initial Catalog=EPlast;Persist Security Info=False;User ID=Admin_EPlast;Password=7PJjTw#VuTZaD8G;MultipleActiveResultSets=False;
we shouldn't change this connection string. it gets from azure. here has to be local one

2021-02-05 16:08 UTC, vovikboyko requested changes

2021-02-05 16:08 UTC, vovikboyko commented on EPlast/EPlast.BLL/Services/Region/RegionService.cs
> +
empty row

2021-02-05 16:08 UTC, vovikboyko commented on EPlast/EPlast.DataAccess/Entities/Region/Region.cs
>  }
still should

2021-02-05 16:10 UTC, AlexKaschuk commented on EPlast/EPlast.WebApi/appsettings.json
> +    "EPlastDBConnection": "Server=tcp:eplast.database.windows.net,1433;Initial Catalog=EPlast;Persist Security Info=False;User ID=Admin_EPlast;Password=7PJjTw#VuTZaD8G;MultipleActiveResultSets=False;
done

2021-02-05 16:10 UTC, AlexKaschuk commented on EPlast/EPlast.WebApi/Controllers/RegionsController.cs
> +            //IEnumerable<RegionDTO> regions = await _cache.GetRecordAsync<IEnumerable<RegionDTO>>(recordKey);
done

2021-02-05 16:10 UTC, AlexKaschuk commented on EPlast/EPlast.WebApi/Controllers/GoverningBodiesController.cs
> +
done

2021-02-05 16:10 UTC, AlexKaschuk commented on EPlast/EPlast.DataAccess/Entities/Region/Region.cs
>  }
done

2021-02-05 16:10 UTC, AlexKaschuk commented on EPlast/EPlast.BLL/Services/Region/RegionService.cs
done

2021-02-05 16:10 UTC, AlexKaschuk commented on EPlast/EPlast.BLL/Interfaces/GoverningBodies/IGoverningBodiesService.cs
> +
done

2021-02-05 16:23 UTC, vovikboyko approved these changes

2021-02-06 10:44 UTC, sooooolo approved these changes

2021-02-06 10:45 UTC, randomVovaKuhot approved these changes

2021-02-06 10:45 UTC, merged