Join city reminder
ita-social-projects/EPlast pull request #861
Opened 2021-02-09 09:14 UTC by vovikboyko

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-02-09 10:28 UTC, AlexKaschuk approved these changes

2021-02-09 10:30 UTC, sooooolo approved these changes

2021-02-09 10:32 UTC, voroniak requested changes

2021-02-09 10:32 UTC, voroniak commented on EPlast/EPlast.BLL/Interfaces/EmailSending/IEmailReminderService.cs
> +        Task JoinCityReminder();
```suggestion
        Task JoinCityReminderAsync();
```

2021-02-09 10:32 UTC, voroniak commented on EPlast/EPlast.BLL/Services/Admin/AdminService.cs
> +            return citiesDTO;
Could you use linq here?

2021-02-09 10:32 UTC, voroniak commented on EPlast/EPlast.BLL/Services/Admin/AdminService.cs
> +        public async Task UpdateUserDatesByChangeRole(string userId, string role)
```suggestion
        public async Task UpdateUserDatesByChangeRoleAsync(string userId, string role)
```

2021-02-09 10:32 UTC, voroniak commented on EPlast/EPlast.BLL/Services/EmailSending/EmailReminderService.cs
> +        public async Task JoinCityReminder()
```suggestion
        public async Task JoinCityReminderAsync()
```

2021-02-09 10:32 UTC, voroniak commented on EPlast/EPlast.BLL/Services/EmailSending/EmailReminderService.cs
> +            }
Could you use linq here?

2021-02-09 10:32 UTC, voroniak commented on EPlast/EPlast.WebApi/Controllers/AuthController.cs
> +                                                    IAuthService authService,
?

2021-02-09 10:32 UTC, voroniak commented on EPlast/EPlast.WebApi/StartupExtensions/AddRecurringJobManager.cs
> +        private static async Task CreateRoles(IServiceProvider serviceProvider, IConfiguration Configuration)
```suggestion
        private static async Task CreateRolesAsync(IServiceProvider serviceProvider, IConfiguration Configuration)
```

2021-02-09 11:28 UTC, vovikboyko commented on EPlast/EPlast.BLL/Services/Admin/AdminService.cs
> +            return citiesDTO;
It's not my code. So, will add this as a new issue.

2021-02-09 11:35 UTC, voroniak commented on EPlast/EPlast.BLL/Services/Admin/AdminService.cs
> +            return citiesDTO;
But you may fix this here

2021-02-09 14:27 UTC, Lunaflumen approved these changes

2021-02-10 17:13 UTC, voroniak requested changes

2021-02-10 17:13 UTC, voroniak commented on EPlast/EPlast.BLL/Services/Admin/AdminService.cs
> +            var allRoles = _roleManager.Roles.Except(admin).OrderBy(i => i.Name).ToList();
why do we have to se .ToList(); here ?

2021-02-10 17:13 UTC, voroniak commented on EPlast/EPlast.WebApi/Controllers/AdminController.cs
> +        public async Task<IActionResult> UsersTable()
```suggestion
        public async Task<IActionResult> GetUsersTable()
```

2021-02-10 17:13 UTC, voroniak commented on EPlast/EPlast.WebApi/Controllers/LoginController.cs
>          private async Task AddEntryMembershipDate(string userId)
```suggestion
        private async Task AddEntryMembershipDateAsync(string userId)
```
Could you also change this ?

2021-02-10 17:24 UTC, vovikboyko commented on EPlast/EPlast.BLL/Services/Admin/AdminService.cs
> +            var allRoles = _roleManager.Roles.Except(admin).OrderBy(i => i.Name).ToList();
fixed

2021-02-10 17:26 UTC, vovikboyko commented on EPlast/EPlast.WebApi/Controllers/AdminController.cs
> +        public async Task<IActionResult> UsersTable()
done

2021-02-10 17:27 UTC, vovikboyko commented on EPlast/EPlast.WebApi/Controllers/LoginController.cs
>          private async Task AddEntryMembershipDate(string userId)
done

2021-02-10 18:23 UTC, voroniak approved these changes
LGTM!

2021-02-10 18:25 UTC, merged