Added more tests for AdminnController
ita-social-projects/EPlast pull request #971
Opened 2021-03-07 17:40 UTC by OlehHatsko

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-03-09 08:14 UTC, sooooolo approved these changes

2021-03-09 09:23 UTC, randomVovaKuhot approved these changes

2021-03-09 12:40 UTC, vovikboyko requested changes

2021-03-09 12:40 UTC, vovikboyko commented on EPlast/EPlast.Tests/Controllers/AdminControllerTests.cs
> +        public async Task GetAdmins_WrongCityId_ReturnBadRequestResult()
Use one same convention fo test naming. Use "Test" ending for every or for non tets.

2021-03-09 13:46 UTC, vovikboyko approved these changes

2021-03-09 18:57 UTC, voroniak requested changes

2021-03-09 18:57 UTC, voroniak commented on EPlast/EPlast.Tests/Controllers/AdminControllerTests.cs
> +            var result = adminController.ChangeCurrentUserRole("user", It.IsAny<string>());
Magic string

2021-03-09 18:57 UTC, voroniak commented on EPlast/EPlast.Tests/Controllers/AdminControllerTests.cs
> +            var result = await adminController.Edit("user");
Magic string

2021-03-09 18:57 UTC, voroniak commented on EPlast/EPlast.Tests/Controllers/AdminControllerTests.cs
> +            var result = await adminController.GetAdmins(0);
Magic number

2021-03-09 18:57 UTC, voroniak commented on EPlast/EPlast.Tests/Controllers/AdminControllerTests.cs
> +            var result = await adminController.GetCityAndRegionAdminsOfUser("user");
Magic string

2021-03-14 08:43 UTC, voroniak approved these changes

2021-03-14 08:47 UTC, merged